package runtime

import (
	"fmt"
	"strings"
	"sync"
)

// registeredEntities is the global list of every entity the user code
// has declared via `Entity.define`. Populated as a side effect of
// `entityDefine` evaluation; consumed by the boot-time migrator to
// know what schema to enforce.
//
// Why a registry instead of walking the program AST: entities are
// captured inside service handler closures and aren't trivially
// reachable from the routes/services lists. Letting the constructor
// register itself is simpler and works for both top-level entity
// bindings and entities created in helpers.
//
// Order is insertion order — useful for reproducible CREATE TABLE
// sequences in tests.
//
// Entries are deduplicated by table name: if the same entity is
// defined twice (typically because of hot-reload), the latest
// declaration wins. Stale entries from prior reloads don't pile up.
var registeredEntities = struct {
	sync.Mutex
	byTable map[string]VEntity
	order   []string
}{byTable: map[string]VEntity{}}

// RegisterEntity adds an entity to the global registry. Called by
// `entityDefine` after constructing the VEntity. Safe to call from
// any goroutine.
func RegisterEntity(e VEntity) {
	registeredEntities.Lock()
	defer registeredEntities.Unlock()
	if _, dup := registeredEntities.byTable[e.Table]; !dup {
		registeredEntities.order = append(registeredEntities.order, e.Table)
	}
	registeredEntities.byTable[e.Table] = e
}

// RegisteredEntities returns a snapshot of every registered entity in
// declaration order. Safe to call concurrently with new registrations
// (returns a copy).
func RegisteredEntities() []VEntity {
	registeredEntities.Lock()
	defer registeredEntities.Unlock()
	out := make([]VEntity, 0, len(registeredEntities.order))
	for _, table := range registeredEntities.order {
		out = append(out, registeredEntities.byTable[table])
	}
	return out
}

// ResetRegisteredEntities clears the registry. Test-only helper for
// hot-reload simulation and isolation between test cases.
func ResetRegisteredEntities() {
	registeredEntities.Lock()
	defer registeredEntities.Unlock()
	registeredEntities.byTable = map[string]VEntity{}
	registeredEntities.order = nil
}

// VEntity is the runtime representation of an Entity declaration. The
// metadata captured here drives the schema migration (CREATE TABLE) and
// the SQL generated by Repo.* operations.
type VEntity struct {
	Table  string
	Fields []EntityField
}

// EntityField describes one column on an entity. The mar-side declaration
// (Entity.serial / Entity.int / etc.) carries the Go type tag; constraints
// like notNull come from the second arg of the column constructor.
type EntityField struct {
	Name    string
	SQLType string // "INTEGER", "TEXT", "BOOLEAN"
	NotNull bool
	Serial  bool // auto-incrementing primary key

	// AcceptedCtors is non-nil when this column was declared with
	// `Entity.enum [Ctor1, Ctor2, ...]`. The strings are the
	// constructor tags in declaration order. SQLType is "TEXT" for
	// enum columns; the values round-trip via the tag. Migration
	// emits a CHECK(name IN ('Ctor1', 'Ctor2', ...)) so the database
	// also enforces the closed set.
	AcceptedCtors []string
}

func (VEntity) isValue() {}
func (e VEntity) Display() string {
	return fmt.Sprintf("<entity:%s>", e.Table)
}

// VColumn is the runtime value produced by Entity.serial / Entity.int /
// Entity.text / Entity.bool / Entity.enum. It's an opaque value the user
// never inspects — Entity.define unpacks it to build the entity's field
// metadata.
type VColumn struct {
	SQLType       string
	NotNull       bool
	Serial        bool
	AcceptedCtors []string // populated by Entity.enum; nil otherwise
}

func (VColumn) isValue() {}
func (c VColumn) Display() string {
	return fmt.Sprintf("<col:%s>", c.SQLType)
}

// VConstraint is the runtime value produced by Entity.notNull. It's
// just a flag — additional constraint builders (Entity.optional /
// Entity.unique) would extend this struct.
type VConstraint struct {
	NotNull bool
}

func (VConstraint) isValue()        {}
func (VConstraint) Display() string { return "<constraint>" }

// entityBuiltins exposes the record-literal schema declaration API:
//
//	Entity.define  : String -> { ...columns } -> Entity a
//	Entity.serial  : Column Int                   -- auto-increment PK
//	Entity.int     : Constraint -> Column Int
//	Entity.text    : Constraint -> Column String
//	Entity.bool    : Constraint -> Column Bool
//	Entity.notNull : Constraint
func entityBuiltins() map[string]Value {
	return map[string]Value{
		"entityDefine": nativeFn(2, func(args []Value) (Value, error) {
			name, ok := args[0].(VString)
			if !ok {
				return nil, fmt.Errorf("Entity.define: expected String table name")
			}
			schema, ok := args[1].(VRecord)
			if !ok {
				return nil, fmt.Errorf("Entity.define: expected schema record (got %T)", args[1])
			}
			fields := make([]EntityField, 0, len(schema.Order))
			for _, fieldName := range schema.Order {
				colVal, ok := schema.Fields[fieldName]
				if !ok {
					return nil, fmt.Errorf("Entity.define: schema missing field %q", fieldName)
				}
				col, ok := colVal.(VColumn)
				if !ok {
					return nil, fmt.Errorf("Entity.define: field %q is not a Column (got %T)", fieldName, colVal)
				}
				fields = append(fields, EntityField{
					Name:          fieldName,
					SQLType:       col.SQLType,
					NotNull:       col.NotNull,
					Serial:        col.Serial,
					AcceptedCtors: col.AcceptedCtors,
				})
			}
			ent := VEntity{Table: name.V, Fields: fields}
			RegisterEntity(ent)
			return ent, nil
		}),

		// Entity.serial is a value (not a function) — it's a fixed column
		// shape: integer primary key with AUTOINCREMENT semantics.
		"entitySerial": VColumn{SQLType: "INTEGER", NotNull: true, Serial: true},

		// Entity.int / .text / .bool take a Constraint arg. The only
		// constraint currently exposed is notNull; the arg keeps room
		// for additional constraints without changing call sites.
		"entityInt":       nativeFn(1, makeColumnConstructor("INTEGER")),
		"entityText":      nativeFn(1, makeColumnConstructor("TEXT")),
		"entityBool":      nativeFn(1, makeColumnConstructor("BOOLEAN")),
		// Stored as INTEGER milliseconds since 1970. The repo
		// encode/decode path round-trips Time values automatically
		// based on this column type, so handlers see Time, never
		// raw integers.
		"entityTimestamp": nativeFn(1, makeColumnConstructor("TIMESTAMP")),

		// Entity.enum [Ctor1, Ctor2, ...] notNull
		// Stored as TEXT; round-trips via the ctor's tag. Validates
		// that every list element is a zero-arg constructor of the
		// same custom type and that tags are unique. Migration
		// emits a CHECK(name IN (...)) so the DB also rejects
		// out-of-set values written by other clients.
		"entityEnum": nativeFn(2, makeEnumColumnConstructor),

		"entityNotNull": VConstraint{NotNull: true},
	}
}

func makeEnumColumnConstructor(args []Value) (Value, error) {
	list, ok := args[0].(VList)
	if !ok {
		return nil, fmt.Errorf("Entity.enum: expected a List of constructors (got %T)", args[0])
	}
	if len(list.Elements) == 0 {
		return nil, fmt.Errorf("Entity.enum: needs at least one accepted constructor")
	}
	tags := make([]string, 0, len(list.Elements))
	seen := map[string]bool{}
	for i, el := range list.Elements {
		ctor, ok := el.(VCtor)
		if !ok {
			return nil, fmt.Errorf("Entity.enum: element %d is not a constructor (got %T)", i, el)
		}
		if len(ctor.Args) != 0 {
			return nil, fmt.Errorf("Entity.enum: constructor %q takes %d args; only zero-arg ctors are supported", ctor.Tag, len(ctor.Args))
		}
		if seen[ctor.Tag] {
			return nil, fmt.Errorf("Entity.enum: duplicate constructor %q in accepted list", ctor.Tag)
		}
		seen[ctor.Tag] = true
		tags = append(tags, ctor.Tag)
	}
	c, ok := args[1].(VConstraint)
	if !ok {
		return nil, fmt.Errorf("Entity.enum: expected Constraint as second arg (got %T)", args[1])
	}
	return VColumn{
		SQLType:       "TEXT",
		NotNull:       c.NotNull,
		AcceptedCtors: tags,
	}, nil
}

func makeColumnConstructor(sqlType string) func([]Value) (Value, error) {
	return func(args []Value) (Value, error) {
		c, ok := args[0].(VConstraint)
		if !ok {
			return nil, fmt.Errorf("column constructor: expected Constraint")
		}
		return VColumn{
			SQLType: sqlType,
			NotNull: c.NotNull,
		}, nil
	}
}

// findField looks up a column by name on the entity. Returns nil if not
// found — callers turn that into a friendly error.
func (e VEntity) findField(name string) *EntityField {
	for i := range e.Fields {
		if e.Fields[i].Name == name {
			return &e.Fields[i]
		}
	}
	return nil
}

// primaryKey returns the field marked Serial. We currently support exactly
// one such field per entity; if missing, queries that need the PK (findById,
// update, delete) error out with a clear message.
func (e VEntity) primaryKey() *EntityField {
	for i := range e.Fields {
		if e.Fields[i].Serial {
			return &e.Fields[i]
		}
	}
	return nil
}

// buildCreateTableSQL generates a CREATE TABLE IF NOT EXISTS statement.
// Constraints supported: NOT NULL, INTEGER PRIMARY KEY AUTOINCREMENT,
// CHECK(name IN (...)) for Entity.enum columns.
func buildCreateTableSQL(e VEntity) string {
	sql := "CREATE TABLE IF NOT EXISTS " + e.Table + " ("
	for i, f := range e.Fields {
		if i > 0 {
			sql += ", "
		}
		// TIMESTAMP is conceptual — store as INTEGER (Unix ms) so
		// SQLite can compare/sort and integers round-trip without
		// timezone or string-format mishaps.
		sqlType := f.SQLType
		if sqlType == "TIMESTAMP" {
			sqlType = "INTEGER"
		}
		sql += f.Name + " " + sqlType
		if f.Serial {
			sql += " PRIMARY KEY AUTOINCREMENT"
		} else if f.NotNull {
			sql += " NOT NULL"
		}
		if f.AcceptedCtors != nil {
			quoted := make([]string, len(f.AcceptedCtors))
			for j, t := range f.AcceptedCtors {
				// Tag values are mar identifiers (alpha/alnum), so the
				// only concern is single quotes; defensively escape.
				quoted[j] = "'" + strings.ReplaceAll(t, "'", "''") + "'"
			}
			sql += " CHECK(" + f.Name + " IN (" + strings.Join(quoted, ", ") + "))"
		}
	}
	sql += ")"
	return sql
}
