package runtime

import (
	"fmt"
	"strings"
	"sync"
)

// registeredEntities is the global list of every entity the user code
// has declared via `Entity.define`. Populated as a side effect of
// `entityDefine` evaluation; consumed by the boot-time migrator to
// know what schema to enforce.
//
// Why a registry instead of walking the program AST: entities are
// captured inside service handler closures and aren't trivially
// reachable from the routes/services lists. Letting the constructor
// register itself is simpler and works for both top-level entity
// bindings and entities created in helpers.
//
// Order is insertion order — useful for reproducible CREATE TABLE
// sequences in tests.
//
// Entries are deduplicated by table name: if the same entity is
// defined twice (typically because of hot-reload), the latest
// declaration wins. Stale entries from prior reloads don't pile up.
var registeredEntities = struct {
	sync.Mutex
	byTable map[string]VEntity
	order   []string
}{byTable: map[string]VEntity{}}

// RegisterEntity adds an entity to the global registry. Called by
// `entityDefine` after constructing the VEntity. Safe to call from
// any goroutine.
//
// Returns an error if the table name is already registered in the
// current evaluation pass. This is the runtime safety net for the
// "no duplicate entity names" invariant — the compile-time lint
// catches collisions of string-literal names; this catches
// everything else (computed names, hot-reload bugs, programmatic
// re-evaluation). Hot-reload is supposed to call ResetForReload
// before re-evaluating the program, which clears the registry; if
// it doesn't, a duplicate registration error here is the canary.
func RegisterEntity(e VEntity) error {
	registeredEntities.Lock()
	defer registeredEntities.Unlock()
	if _, dup := registeredEntities.byTable[e.Table]; dup {
		return fmt.Errorf(
			"Entity.define: name %q is declared more than once in this build.\n"+
				"  Each entity must have a unique table name. Look for another\n"+
				"  Entity.define call with the same name in your code.",
			e.Table)
	}
	registeredEntities.order = append(registeredEntities.order, e.Table)
	registeredEntities.byTable[e.Table] = e
	return nil
}

// RegisteredEntities returns a snapshot of every registered entity in
// declaration order. Safe to call concurrently with new registrations
// (returns a copy).
func RegisteredEntities() []VEntity {
	registeredEntities.Lock()
	defer registeredEntities.Unlock()
	out := make([]VEntity, 0, len(registeredEntities.order))
	for _, table := range registeredEntities.order {
		out = append(out, registeredEntities.byTable[table])
	}
	return out
}

// ResetRegisteredEntities clears the registry. Test-only helper for
// hot-reload simulation and isolation between test cases.
func ResetRegisteredEntities() {
	registeredEntities.Lock()
	defer registeredEntities.Unlock()
	registeredEntities.byTable = map[string]VEntity{}
	registeredEntities.order = nil
}

// ResetForReload clears every package-level registry that a fresh
// compile (mar dev hot reload, or a one-shot mar migrate command)
// should not inherit from a previous run: the entity registry, the
// migration cache, and the enum-type table used by typed Path
// patterns. Wraps three separate calls so adding a fourth global
// later is a one-place change.
func ResetForReload() {
	ResetRegisteredEntities()
	ResetMigrationCache()
	ResetEnumTypes()
}

// VEntity is the runtime representation of an Entity declaration. The
// metadata captured here drives the schema migration (CREATE TABLE) and
// the SQL generated by Repo.* operations.
type VEntity struct {
	Table  string
	Fields []EntityField

	// UniqueIndexes lists the composite (and single-column) UNIQUE
	// constraints declared via `Entity.unique [cols...]`. Each inner
	// slice is one constraint — a single index covers all columns in
	// the slice together. Order inside an index matches the user's
	// declaration so error messages and index names stay predictable.
	// The migrator emits one `CREATE UNIQUE INDEX IF NOT EXISTS` per
	// entry; SQLite enforces the uniqueness across the column tuple.
	//
	// Empty (nil or len 0) means the entity has no extra unique
	// constraints beyond the implicit one on the serial PK.
	UniqueIndexes [][]string
}

// EntityField describes one column on an entity. The mar-side declaration
// (Entity.serial / Entity.int / etc.) carries the Go type tag; constraints
// like notNull come from the second arg of the column constructor.
type EntityField struct {
	Name    string
	SQLType string // "INTEGER", "TEXT", "BOOLEAN"
	NotNull bool
	Serial  bool // auto-incrementing primary key

	// AcceptedCtors is non-nil when this column was declared with
	// `Entity.enum [Ctor1, Ctor2, ...]`. The strings are the
	// constructor tags in declaration order. SQLType is "TEXT" for
	// enum columns; the values round-trip via the tag. Migration
	// emits a CHECK(name IN ('Ctor1', 'Ctor2', ...)) so the database
	// also enforces the closed set.
	AcceptedCtors []string
}

func (VEntity) isValue() {}
func (e VEntity) Display() string {
	return fmt.Sprintf("<entity:%s>", e.Table)
}

// VColumn is the runtime value produced by Entity.serial / Entity.int /
// Entity.text / Entity.bool / Entity.enum. It's an opaque value the user
// never inspects — Entity.define unpacks it to build the entity's field
// metadata.
type VColumn struct {
	SQLType       string
	NotNull       bool
	Serial        bool
	AcceptedCtors []string // populated by Entity.enum; nil otherwise
}

func (VColumn) isValue() {}
func (c VColumn) Display() string {
	return fmt.Sprintf("<col:%s>", c.SQLType)
}

// VConstraint is the runtime value produced by Entity.notNull. It's
// just a flag — additional constraint builders (Entity.optional /
// Entity.foreign) would extend this struct.
type VConstraint struct {
	NotNull bool
}

func (VConstraint) isValue()        {}
func (VConstraint) Display() string { return "<constraint>" }

// entityBuiltins exposes the record-literal schema declaration API:
//
//	Entity.define  : { name : String, columns : c, uniques : List (List String) } -> Entity a
//	Entity.serial  : Column Int                   -- auto-increment PK
//	Entity.int     : Constraint -> Column Int
//	Entity.text    : Constraint -> Column String
//	Entity.bool    : Constraint -> Column Bool
//	Entity.notNull : Constraint
func entityBuiltins() map[string]Value {
	return map[string]Value{
		"entityDefine": nativeFn(1, entityDefineImpl),

		// Entity.serial is a value (not a function) — it's a fixed column
		// shape: integer primary key with AUTOINCREMENT semantics.
		"entitySerial": VColumn{SQLType: "INTEGER", NotNull: true, Serial: true},

		// Entity.int / .text / .bool take a Constraint arg. The only
		// constraint currently exposed is notNull; the arg keeps room
		// for additional constraints without changing call sites.
		"entityInt":  nativeFn(1, makeColumnConstructor("INTEGER")),
		"entityText": nativeFn(1, makeColumnConstructor("TEXT")),
		"entityBool": nativeFn(1, makeColumnConstructor("BOOLEAN")),
		// Stored as INTEGER milliseconds since 1970. The repo
		// encode/decode path round-trips Time values automatically
		// based on this column type, so handlers see Time, never
		// raw integers.
		"entityTimestamp": nativeFn(1, makeColumnConstructor("TIMESTAMP")),

		// Entity.enum [Ctor1, Ctor2, ...] notNull
		// Stored as TEXT; round-trips via the ctor's tag. Validates
		// that every list element is a zero-arg constructor of the
		// same custom type and that tags are unique. Migration
		// emits a CHECK(name IN (...)) so the DB also rejects
		// out-of-set values written by other clients.
		"entityEnum": nativeFn(2, makeEnumColumnConstructor),

		"entityNotNull": VConstraint{NotNull: true},
	}
}

// entityDefineImpl is the runtime for Entity.define. The single
// argument is a record with three fields:
//
//   - name    : String          — table name, becomes Table on the entity
//   - columns : { ...c }        — record of column declarations
//   - uniques : List (List String) — composite unique constraints
//
// Every column declaration must be a VColumn (produced by
// Entity.serial / Entity.int / Entity.text / Entity.bool /
// Entity.enum / Entity.timestamp). Anything else fails fast with the
// offending field name.
//
// Validation:
//   - name must be non-empty
//   - name must match a portable identifier shape ([A-Za-z_][A-Za-z0-9_]*)
//   - name cannot start with reserved prefixes (`sqlite_` is SQLite-internal,
//     `_mar_` is the framework's own namespace for things like
//     `_mar_admins`, `_mar_schema_migrations`)
//   - every uniques entry references a column declared on the entity
//   - no duplicate column names within a single unique index
//   - no two indexes with the exact same column list (idempotent)
//
// Compile-time linting catches name violations earlier when the name
// is a string literal; this runtime check is the safety net for
// computed names and for paths the lint hasn't seen.
//
// After construction, RegisterEntity is called. RegisterEntity errors
// if the table name is already in the registry — that's the "no
// duplicate entity declarations within one program evaluation"
// invariant. Hot-reload calls ResetForReload before re-evaluating, so
// reloads still work.
func entityDefineImpl(args []Value) (Value, error) {
	spec, ok := args[0].(VRecord)
	if !ok {
		return nil, fmt.Errorf("Entity.define: expected a record (got %T)", args[0])
	}

	// --- name ---
	nameVal, ok := spec.Fields["name"]
	if !ok {
		return nil, fmt.Errorf("Entity.define: spec missing required field `name`")
	}
	name, ok := nameVal.(VString)
	if !ok {
		return nil, fmt.Errorf("Entity.define: `name` must be a String (got %T)", nameVal)
	}
	if err := validateEntityName(name.V); err != nil {
		return nil, err
	}

	// --- columns ---
	colsVal, ok := spec.Fields["columns"]
	if !ok {
		return nil, fmt.Errorf("Entity.define %q: spec missing required field `columns`", name.V)
	}
	schema, ok := colsVal.(VRecord)
	if !ok {
		return nil, fmt.Errorf("Entity.define %q: `columns` must be a record (got %T)", name.V, colsVal)
	}
	fields := make([]EntityField, 0, len(schema.Order))
	for _, fieldName := range schema.Order {
		colVal, ok := schema.Fields[fieldName]
		if !ok {
			return nil, fmt.Errorf("Entity.define %q: columns missing field %q", name.V, fieldName)
		}
		col, ok := colVal.(VColumn)
		if !ok {
			return nil, fmt.Errorf("Entity.define %q: column %q is not a Column (got %T)", name.V, fieldName, colVal)
		}
		fields = append(fields, EntityField{
			Name:          fieldName,
			SQLType:       col.SQLType,
			NotNull:       col.NotNull,
			Serial:        col.Serial,
			AcceptedCtors: col.AcceptedCtors,
		})
	}

	// --- uniques ---
	uniqueIndexes, err := parseUniquesSpec(spec, name.V, fields)
	if err != nil {
		return nil, err
	}

	// --- register ---
	ent := VEntity{Table: name.V, Fields: fields, UniqueIndexes: uniqueIndexes}
	if err := RegisterEntity(ent); err != nil {
		return nil, err
	}
	return ent, nil
}

// validateEntityName enforces the runtime portion of the table-name
// rules. The compile-time lint pass enforces the same rules earlier
// when the name is a string literal; this is the fallback for
// computed names or for paths the lint hasn't reached.
func validateEntityName(name string) error {
	if name == "" {
		return fmt.Errorf("Entity.define: name cannot be empty")
	}
	if strings.HasPrefix(name, "sqlite_") {
		return fmt.Errorf("Entity.define: name %q starts with reserved prefix `sqlite_` (SQLite-internal)", name)
	}
	if strings.HasPrefix(name, "_mar_") {
		return fmt.Errorf("Entity.define: name %q starts with reserved prefix `_mar_` (framework-internal)", name)
	}
	for i, r := range name {
		isLetter := (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r == '_'
		isDigit := r >= '0' && r <= '9'
		if i == 0 {
			if !isLetter {
				return fmt.Errorf("Entity.define: name %q must start with a letter or underscore (got %q)", name, r)
			}
		} else if !isLetter && !isDigit {
			return fmt.Errorf("Entity.define: name %q contains invalid character %q (allowed: letters, digits, underscore)", name, r)
		}
	}
	return nil
}

// parseUniquesSpec reads the `uniques` field off the entity spec
// record, validates every entry references a real column, and
// returns the resulting [][]string ready to live on VEntity.
//
// The field is required (the design choice from the redesign: every
// entity declares it explicitly, even if empty). An empty list is
// the "no extra uniques" signal.
func parseUniquesSpec(spec VRecord, table string, fields []EntityField) ([][]string, error) {
	uniqVal, ok := spec.Fields["uniques"]
	if !ok {
		return nil, fmt.Errorf("Entity.define %q: spec missing required field `uniques` (use [] for none)", table)
	}
	outer, ok := uniqVal.(VList)
	if !ok {
		return nil, fmt.Errorf("Entity.define %q: `uniques` must be a List of column-name lists (got %T)", table, uniqVal)
	}
	knownFieldNames := map[string]bool{}
	for _, f := range fields {
		knownFieldNames[f.Name] = true
	}
	out := make([][]string, 0, len(outer.Elements))
	for i, indexVal := range outer.Elements {
		innerList, ok := indexVal.(VList)
		if !ok {
			return nil, fmt.Errorf("Entity.define %q: uniques[%d] is not a List of column names (got %T)", table, i, indexVal)
		}
		if len(innerList.Elements) == 0 {
			return nil, fmt.Errorf("Entity.define %q: uniques[%d] is empty (a unique index needs at least one column)", table, i)
		}
		cols := make([]string, 0, len(innerList.Elements))
		seenInIndex := map[string]bool{}
		for j, colVal := range innerList.Elements {
			s, ok := colVal.(VString)
			if !ok {
				return nil, fmt.Errorf("Entity.define %q: uniques[%d][%d] is not a String (got %T)", table, i, j, colVal)
			}
			if seenInIndex[s.V] {
				return nil, fmt.Errorf("Entity.define %q: uniques[%d] has duplicate column %q in the same index", table, i, s.V)
			}
			if !knownFieldNames[s.V] {
				available := make([]string, len(fields))
				for k, f := range fields {
					available[k] = f.Name
				}
				return nil, fmt.Errorf("Entity.define %q: uniques[%d] references column %q which is not declared on this entity (available: %s)",
					table, i, s.V, strings.Join(available, ", "))
			}
			seenInIndex[s.V] = true
			cols = append(cols, s.V)
		}
		// Dedup against earlier index declarations on the same
		// entity. Same column list (same order) collapses to one.
		duplicate := false
		for _, prior := range out {
			if equalStringSlice(prior, cols) {
				duplicate = true
				break
			}
		}
		if !duplicate {
			out = append(out, cols)
		}
	}
	return out, nil
}

// equalStringSlice reports whether two []string have identical
// length and element-wise equality. Used by parseUniquesSpec to
// dedup unique-index declarations within a single Entity.define.
func equalStringSlice(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func makeEnumColumnConstructor(args []Value) (Value, error) {
	list, ok := args[0].(VList)
	if !ok {
		return nil, fmt.Errorf("Entity.enum: expected a List of constructors (got %T)", args[0])
	}
	if len(list.Elements) == 0 {
		return nil, fmt.Errorf("Entity.enum: needs at least one accepted constructor")
	}
	tags := make([]string, 0, len(list.Elements))
	seen := map[string]bool{}
	for i, el := range list.Elements {
		ctor, ok := el.(VCtor)
		if !ok {
			return nil, fmt.Errorf("Entity.enum: element %d is not a constructor (got %T)", i, el)
		}
		if len(ctor.Args) != 0 {
			return nil, fmt.Errorf("Entity.enum: constructor %q takes %d args; only zero-arg ctors are supported", ctor.Tag, len(ctor.Args))
		}
		if seen[ctor.Tag] {
			return nil, fmt.Errorf("Entity.enum: duplicate constructor %q in accepted list", ctor.Tag)
		}
		seen[ctor.Tag] = true
		tags = append(tags, ctor.Tag)
	}
	c, ok := args[1].(VConstraint)
	if !ok {
		return nil, fmt.Errorf("Entity.enum: expected Constraint as second arg (got %T)", args[1])
	}
	return VColumn{
		SQLType:       "TEXT",
		NotNull:       c.NotNull,
		AcceptedCtors: tags,
	}, nil
}

func makeColumnConstructor(sqlType string) func([]Value) (Value, error) {
	return func(args []Value) (Value, error) {
		c, ok := args[0].(VConstraint)
		if !ok {
			return nil, fmt.Errorf("column constructor: expected Constraint")
		}
		return VColumn{
			SQLType: sqlType,
			NotNull: c.NotNull,
		}, nil
	}
}

// findField looks up a column by name on the entity. Returns nil if not
// found — callers turn that into a friendly error.
func (e VEntity) findField(name string) *EntityField {
	for i := range e.Fields {
		if e.Fields[i].Name == name {
			return &e.Fields[i]
		}
	}
	return nil
}

// primaryKey returns the field marked Serial. We currently support exactly
// one such field per entity; if missing, queries that need the PK (findById,
// update, delete) error out with a clear message.
func (e VEntity) primaryKey() *EntityField {
	for i := range e.Fields {
		if e.Fields[i].Serial {
			return &e.Fields[i]
		}
	}
	return nil
}

// buildCreateTableSQL generates a CREATE TABLE IF NOT EXISTS statement.
// Constraints supported: NOT NULL, INTEGER PRIMARY KEY AUTOINCREMENT,
// CHECK(name IN (...)) for Entity.enum columns.
func buildCreateTableSQL(e VEntity) string {
	sql := "CREATE TABLE IF NOT EXISTS " + e.Table + " ("
	for i, f := range e.Fields {
		if i > 0 {
			sql += ", "
		}
		// TIMESTAMP is conceptual — store as INTEGER (Unix ms) so
		// SQLite can compare/sort and integers round-trip without
		// timezone or string-format mishaps.
		sqlType := f.SQLType
		if sqlType == "TIMESTAMP" {
			sqlType = "INTEGER"
		}
		sql += f.Name + " " + sqlType
		if f.Serial {
			sql += " PRIMARY KEY AUTOINCREMENT"
		} else if f.NotNull {
			sql += " NOT NULL"
		}
		if f.AcceptedCtors != nil {
			quoted := make([]string, len(f.AcceptedCtors))
			for j, t := range f.AcceptedCtors {
				// Tag values are mar identifiers (alpha/alnum), so the
				// only concern is single quotes; defensively escape.
				quoted[j] = "'" + strings.ReplaceAll(t, "'", "''") + "'"
			}
			sql += " CHECK(" + f.Name + " IN (" + strings.Join(quoted, ", ") + "))"
		}
	}
	sql += ")"
	return sql
}
