// Package mathgen computes the one table the `Math` module is built on — a
// quarter wave of sine, sampled every deci-degree — and emits it as literal
// source into all three runtimes.
//
// The point is that the table is computed ONCE, here, at generation time, and
// never recomputed per platform. `Math.sin` must return the same integer in
// Go, in the browser and on iOS, because a replayed rules engine (lendas), a
// bot that proves a level is beatable (pulse-runner) and time travel all
// assume it. Calling each platform's libm would put three different
// implementations of sin between the program and its answer; a checked-in
// table removes the platform from the question entirely. Floating point is
// used below and nowhere downstream: the generated integers ARE the spec.
//
// The outputs are:
//
//   - internal/runtime/math_table_gen.go                        (whole file)
//   - internal/jsserve/runtime.js                               (a marked region)
//   - internal/iosbundle/template/Sources/MarMathTable.swift    (whole file)
//
// and the staleness test in this package fails whenever a committed copy
// disagrees with what this code produces — the same lock ctorgen puts on the
// builtin constructor registry. To change the table, edit this file and run
//
//	go generate ./internal/mathgen
//
//go:generate go run ./cmd
package mathgen

import (
	"fmt"
	"go/format"
	"math"
	"strings"
)

// Quarter is the number of deci-degrees in a quarter turn, and Full the
// number in a whole one. Deci-degrees is the internal resolution of `Angle`:
// with a ×1000 output, sine near 0° moves about 1.7 units per deci-degree, so
// whole degrees would waste output resolution (17 units per step — visible
// stutter when a raycaster turns) and milli-degrees would be false precision.
// See docs/proposals/math.md, "Why deci-degrees is the internal resolution".
const (
	Quarter = 900
	Full    = 3600
	// Scale is the output scale of sin/cos: ×1000, not ×1024. The power of
	// two buys nothing without a shift operator (`// 1024` costs exactly what
	// `// 1000` costs and reads worse), and every other continuous quantity
	// in the language is already decimal — Canvas.Alpha, Canvas.Scale and
	// Sound.volume all speak percent.
	Scale = 1000
)

// SinQuarter returns sin sampled at every deci-degree from 0.0° to 90.0°
// inclusive — 901 entries, each roundHalfEven(sin(θ) × 1000), so 0 at the
// start and exactly 1000 at the end.
//
// Half-even rounding, because that is `Decimal`'s default (ADR 0004) and the
// language has one rounding doctrine rather than two. The quarter wave is
// enough for the whole circle: the kernels fold the other three quadrants
// onto it, which is also what makes `sin`, `cos` and `atan2` structurally
// unable to disagree about where 45.0° is.
func SinQuarter() []int {
	out := make([]int, Quarter+1)
	for d := 0; d <= Quarter; d++ {
		rad := float64(d) / 10 * math.Pi / 180
		out[d] = int(math.RoundToEven(math.Sin(rad) * Scale))
	}
	return out
}

// rows renders the table as numbers, `perRow` to a line, each line prefixed
// with `indent`. Wrapping keeps a regenerated table diffable: a changed entry
// shows up as one changed line instead of one changed 4KB line.
func rows(values []int, indent string, perRow int, sep string) string {
	var b strings.Builder
	for i, v := range values {
		if i%perRow == 0 {
			if i > 0 {
				b.WriteString("\n")
			}
			b.WriteString(indent)
		} else {
			b.WriteString(" ")
		}
		fmt.Fprintf(&b, "%d%s", v, sep)
	}
	return b.String()
}

const tableBlurb = "" +
	"// sin(θ) × 1000, half-even, at every deci-degree from 0.0° to 90.0°.\n" +
	"// 901 entries: index i is i/10 degrees, sinQuarter[900] is exactly 1000.\n" +
	"// The other three quadrants fold onto this one; atan2 searches the same\n" +
	"// numbers, so it cannot disagree with sin about where an angle is.\n"

// GoFile renders the whole of internal/runtime/math_table_gen.go.
func GoFile() string {
	var b strings.Builder
	b.WriteString("// Code generated by internal/mathgen; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// The quarter-wave sine table behind the Math module, computed once at\n")
	b.WriteString("// generation time and shared verbatim by all three runtimes. To change it,\n")
	b.WriteString("// edit internal/mathgen and run: go generate ./internal/mathgen\n\n")
	b.WriteString("package runtime\n\n")
	b.WriteString(strings.ReplaceAll(tableBlurb, "// ", "// "))
	fmt.Fprintf(&b, "var sinQuarter = [%d]int64{\n", Quarter+1)
	b.WriteString(rows(SinQuarter(), "\t", 12, ","))
	b.WriteString("\n}\n")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		panic(fmt.Sprintf("mathgen: generated Go does not parse: %v", err))
	}
	return string(formatted)
}

// JS region markers in internal/jsserve/runtime.js. The generator replaces
// everything between them; the marker lines themselves stay.
const (
	JSBegin = "  // BEGIN GENERATED SINE TABLE (go generate ./internal/mathgen) — DO NOT EDIT"
	JSEnd   = "  // END GENERATED SINE TABLE"
)

// JSRegion renders the full marked region for runtime.js, markers included.
func JSRegion() string {
	var b strings.Builder
	b.WriteString(JSBegin + "\n")
	b.WriteString("  " + strings.ReplaceAll(strings.TrimSuffix(tableBlurb, "\n"), "\n", "\n  ") + "\n")
	b.WriteString("  const SIN_QUARTER = [\n")
	b.WriteString(rows(SinQuarter(), "    ", 16, ","))
	b.WriteString("\n  ];\n")
	b.WriteString(JSEnd)
	return b.String()
}

// SwiftFile renders the whole of MarMathTable.swift.
func SwiftFile() string {
	var b strings.Builder
	b.WriteString("// Code generated by internal/mathgen; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// The quarter-wave sine table behind the Math module, computed once at\n")
	b.WriteString("// generation time and shared verbatim by all three runtimes. To change it,\n")
	b.WriteString("// edit internal/mathgen and run: go generate ./internal/mathgen\n\n")
	b.WriteString("enum MarMathTable {\n")
	b.WriteString("    " + strings.ReplaceAll(strings.TrimSuffix(tableBlurb, "\n"), "\n", "\n    ") + "\n")
	b.WriteString("    static let sinQuarter: [Int] = [\n")
	b.WriteString(rows(SinQuarter(), "        ", 12, ","))
	b.WriteString("\n    ]\n")
	b.WriteString("}\n")
	return b.String()
}

// SpliceJS returns src with the marked region replaced by the current
// JSRegion. It errors if the markers are missing or out of order.
func SpliceJS(src string) (string, error) {
	begin := strings.Index(src, JSBegin)
	end := strings.Index(src, JSEnd)
	if begin < 0 || end < 0 || end < begin {
		return "", fmt.Errorf("mathgen: BEGIN/END GENERATED SINE TABLE markers not found (or reversed) in runtime.js")
	}
	return src[:begin] + JSRegion() + src[end+len(JSEnd):], nil
}
