package iosbundle

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// fullSpec returns a Spec with every required field populated, so
// individual tests can override the bit they care about without
// repeating the boilerplate of all the others.
func fullSpec() Spec {
	return Spec{
		AppName:          "Notes Fullstack",
		BundleID:         "com.example.notes",
		DisplayName:      "Notes Fullstack",
		MarketingVersion: "1.2.3",
		BuildNumber:      "42",
		DefaultBaseURL:   "https://notes.example.com",
		MarVersion:       "test",
	}
}

// TestGenerateMaterializesXcodeProject pins the contract of the
// template materialization step: a single Generate call produces
// a Xcode-openable project tree under outDir, with all placeholders
// substituted in both file content and file paths, and without
// leaking maintainer-only files (project.yml) into the user's
// output.
//
// This is the spec for the xcodegen-free runtime: end users never
// run xcodegen, so iosbundle has to deliver a complete .xcodeproj
// directly from the embedded template.
func TestGenerateMaterializesXcodeProject(t *testing.T) {
	outDir := t.TempDir()
	projectDir, err := Generate(fullSpec(), outDir)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	// AppName "Notes Fullstack" → SwiftIdentifier "NotesFullstack"
	// → projectDir = <outDir>/NotesFullstack.
	wantProjectDir := filepath.Join(outDir, "NotesFullstack")
	if projectDir != wantProjectDir {
		t.Errorf("projectDir = %q, want %q", projectDir, wantProjectDir)
	}

	// (a) Path substitution: the .xcodeproj directory must end up
	// renamed from "__MAR_APP_NAME__.xcodeproj" to "NotesFullstack.xcodeproj".
	xcodeproj := filepath.Join(projectDir, "NotesFullstack.xcodeproj", "project.pbxproj")
	if _, err := os.Stat(xcodeproj); err != nil {
		t.Errorf("expected %s to exist after Generate: %v", xcodeproj, err)
	}
	// And the unsubstituted name must NOT exist.
	stalePath := filepath.Join(projectDir, "__MAR_APP_NAME__.xcodeproj")
	if _, err := os.Stat(stalePath); !os.IsNotExist(err) {
		t.Errorf("expected %s to be absent (path substitution should have renamed it)", stalePath)
	}

	// (b) project.yml is xcodegen input, not user output. Must not
	// leak through the materialization walk.
	if _, err := os.Stat(filepath.Join(projectDir, "project.yml")); !os.IsNotExist(err) {
		t.Errorf("project.yml should not be materialized to the user's output")
	}

	// (c) Content substitution: every placeholder lands in the
	// pbxproj as the substituted value; no raw placeholder leaks.
	pbxBytes, err := os.ReadFile(xcodeproj)
	if err != nil {
		t.Fatalf("read pbxproj: %v", err)
	}
	pbx := string(pbxBytes)
	for _, raw := range []string{
		"__MAR_APP_NAME__",
		"__MAR_BUNDLE_ID__",
		"__MAR_DISPLAY_NAME__",
		"__MAR_MARKETING_VERSION__",
		"__MAR_BUILD_NUMBER__",
		"__MAR_DEFAULT_BASE_URL__",
	} {
		if strings.Contains(pbx, raw) {
			t.Errorf("project.pbxproj contains unsubstituted %s", raw)
		}
	}
	for _, want := range []string{
		"NotesFullstack",    // SwiftIdentifier app name
		"com.example.notes", // BundleID
		"1.2.3",             // MarketingVersion
		"42",                // BuildNumber
	} {
		if !strings.Contains(pbx, want) {
			t.Errorf("project.pbxproj should reference %q", want)
		}
	}

	// (d) Info.plist substitutions: DisplayName goes in literally
	// (Apple home-screen label), MarBaseURL is the production URL.
	infoBytes, err := os.ReadFile(filepath.Join(projectDir, "Info.plist"))
	if err != nil {
		t.Fatalf("read Info.plist: %v", err)
	}
	info := string(infoBytes)
	for _, want := range []string{
		"Notes Fullstack",           // DisplayName literal (with space)
		"https://notes.example.com", // DefaultBaseURL
	} {
		if !strings.Contains(info, want) {
			t.Errorf("Info.plist should contain %q", want)
		}
	}
	for _, raw := range []string{
		"__MAR_DISPLAY_NAME__",
		"__MAR_DEFAULT_BASE_URL__",
	} {
		if strings.Contains(info, raw) {
			t.Errorf("Info.plist contains unsubstituted %s", raw)
		}
	}

	// (e) Swift files get the auto-generated header prepended.
	mainSwift, err := os.ReadFile(filepath.Join(projectDir, "Sources", "MarRuntimeIOSApp.swift"))
	if err != nil {
		t.Fatalf("read MarRuntimeIOSApp.swift: %v", err)
	}
	if !strings.HasPrefix(string(mainSwift), "// Generated by Mar (test)") {
		t.Errorf("Swift file should start with the auto-generated header, got: %q",
			firstLine(string(mainSwift)))
	}
}

// TestGenerateRejectsMissingIdentityFields proves Generate is the
// last line of defense against bundles with placeholder identity.
// scaffold.BuildIOS validates against mar.json with a richer error,
// but if a direct caller skips that step, Generate refuses to
// silently fabricate values.
func TestGenerateRejectsMissingIdentityFields(t *testing.T) {
	cases := []struct {
		name    string
		mutate  func(*Spec)
		wantSub string
	}{
		{"bundle id missing", func(s *Spec) { s.BundleID = "" }, "BundleID"},
		{"display name missing", func(s *Spec) { s.DisplayName = "" }, "DisplayName"},
		{"marketing version missing", func(s *Spec) { s.MarketingVersion = "" }, "MarketingVersion"},
		{"build number missing", func(s *Spec) { s.BuildNumber = "" }, "BuildNumber"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			spec := fullSpec()
			tc.mutate(&spec)
			_, err := Generate(spec, t.TempDir())
			if err == nil {
				t.Fatal("Generate accepted incomplete spec")
			}
			if !strings.Contains(err.Error(), tc.wantSub) {
				t.Errorf("error %q should mention %q", err, tc.wantSub)
			}
		})
	}
}

// TestGenerateEmbedsProgramJSON covers the path that writes the
// compiled program.json snapshot into Resources/ for instant
// cold-start (Approach C).
func TestGenerateEmbedsProgramJSON(t *testing.T) {
	outDir := t.TempDir()
	want := []byte(`{"entry":"main","modules":[]}`)
	spec := fullSpec()
	spec.EmbeddedProgram = want
	projectDir, err := Generate(spec, outDir)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	got, err := os.ReadFile(filepath.Join(projectDir, "Resources", "program.json"))
	if err != nil {
		t.Fatalf("read program.json: %v", err)
	}
	if string(got) != string(want) {
		t.Errorf("program.json mismatch:\n got: %s\nwant: %s", got, want)
	}
}

func TestSwiftIdentifier(t *testing.T) {
	cases := []struct{ in, want string }{
		{"notes-fullstack", "NotesFullstack"},
		{"my app v2", "MyAppV2"},
		{"123demo", "App123demo"},
		{"", ""},
		{"---", ""},
	}
	for _, tc := range cases {
		if got := SwiftIdentifier(tc.in); got != tc.want {
			t.Errorf("SwiftIdentifier(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}
