// Package iosbundle materializes a generated Xcode project from an
// embedded template, substituting per-app config (display name, bundle
// id, baseURL).
//
// The Swift code is intentionally generic: it discovers what the mar
// backend exposes via /_mar/schema on cold start and renders generic
// UI for it. The "build" only needs to bake three things into the
// scaffold:
//
//   - app display name → Info.plist + pbxproj + @main struct name
//   - bundle id        → pbxproj
//   - default base URL → Info.plist (DEBUG builds also accept Bonjour
//     discovery; RELEASE uses the baked URL exclusively)
//
// Output layout under outDir:
//
//	<AppName>/
//	  <AppName>.xcodeproj/    ← ready to open in Xcode
//	  Info.plist
//	  README.md
//	  Sources/
//	    MarRuntimeIOSApp.swift
//	    AppViewModel.swift
//	    APIClient.swift
//	    ContentView.swift
//	    Discovery.swift       (DEBUG only: Bonjour browsing)
//	    MarLoader.swift, …    (mar interpreter + page runtime)
//
// The .xcodeproj and Info.plist files in the embedded template are
// generated by xcodegen as part of `make build` (see the Makefile's
// `ios-template` rule). End users of mar never need xcodegen installed
// — they receive the pre-generated artifacts via go:embed, and
// `mar build --target ios` just materializes the template with
// substitutions. The operator opens the resulting .xcodeproj in Xcode,
// signs, and builds. From then on, any changes to the mar backend show
// up in the app on cold start without any iOS rebuild.
package iosbundle

import (
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

//go:embed all:template
var templateFS embed.FS

// Spec is the per-app config baked into the generated project.
//
// All identity fields (AppName, BundleID, DisplayName,
// MarketingVersion, BuildNumber) are required: Generate refuses
// to materialize a bundle with placeholder identity, because the
// resulting .ipa would fail App Store review or silently overwrite
// another developer's identifier. Caller-side validation against
// mar.json (see scaffold.BuildIOS) produces a richer error with a
// paste-ready suggestion; the checks here are the last line of
// defense for direct callers that bypass scaffold.
type Spec struct {
	// AppName is the project's human-readable name from
	// manifest.Name (e.g. "notes-fullstack"). Used for the Swift
	// @main struct, the Xcode target, and the scheme — passed
	// through SwiftIdentifier before being substituted (e.g.
	// "notes-fullstack" → "NotesFullstack"). Different from
	// DisplayName, which is the user-facing label on the home
	// screen and may contain spaces / accents.
	AppName string

	// BundleID is the iOS bundle identifier (reverse-DNS). Required.
	// Baked into the generated .pbxproj as PRODUCT_BUNDLE_IDENTIFIER.
	BundleID string

	// DisplayName is the home-screen label (CFBundleDisplayName).
	// Required. Allowed to differ from AppName — typically the
	// literal manifest.name rather than the SwiftIdentifier mangle.
	DisplayName string

	// MarketingVersion is the user-facing version string ("1.2.3").
	// Required. Goes into the .pbxproj as MARKETING_VERSION.
	MarketingVersion string

	// BuildNumber is the internal build counter ("1", "42", …).
	// Required. Goes into the .pbxproj as CURRENT_PROJECT_VERSION.
	BuildNumber string

	// DefaultBaseURL is baked into Info.plist as MarBaseURL. In
	// RELEASE builds this is the only target the app talks to; in
	// DEBUG, Bonjour discovery on the LAN supersedes it when a
	// `_mar._tcp` service is found (auto-connecting to `mar dev`
	// running on the same network). Empty falls back to
	// http://localhost:3000 — the only field with a default,
	// because dev/sideload builds against a Bonjour-discovered
	// `mar dev` legitimately don't need a production URL.
	DefaultBaseURL string

	// MarVersion is stamped into the per-file Swift header so anyone
	// looking at the generated code knows which `mar` produced it
	// (and that hand-editing won't survive the next build). Empty =
	// "dev" (matches cmd/mar/main.go's fallback).
	MarVersion string

	// EmbeddedProgram is the compiled program.json bytes for the
	// user's app. Written to Resources/program.json in the generated
	// project; the Swift loader reads it synchronously at cold-start
	// so the first frame paints instantly even before the network
	// fetch returns. Empty = embedded fallback omitted (Swift falls
	// back to fetching only).
	EmbeddedProgram []byte
}

// Generate writes the substituted template to outDir/<AppName>/. Any
// existing contents at that path are overwritten (the iOS scaffold is
// always considered disposable).
func Generate(spec Spec, outDir string) (projectDir string, err error) {
	if spec.AppName == "" {
		return "", fmt.Errorf("iosbundle: AppName is required")
	}
	swiftName := SwiftIdentifier(spec.AppName)
	if swiftName == "" {
		return "", fmt.Errorf("iosbundle: AppName %q has no valid Swift-identifier characters", spec.AppName)
	}
	// Identity fields have no defaults: see the Spec doc comment.
	// scaffold.BuildIOS validates against mar.json before calling
	// Generate, so reaching these branches means a direct caller
	// passed an incomplete spec.
	for _, req := range []struct{ name, value string }{
		{"BundleID", spec.BundleID},
		{"DisplayName", spec.DisplayName},
		{"MarketingVersion", spec.MarketingVersion},
		{"BuildNumber", spec.BuildNumber},
	} {
		if req.value == "" {
			return "", fmt.Errorf("iosbundle: %s is required", req.name)
		}
	}
	if spec.DefaultBaseURL == "" {
		spec.DefaultBaseURL = "http://localhost:3000"
	}

	projectDir = filepath.Join(outDir, swiftName)
	if err := os.RemoveAll(projectDir); err != nil {
		return "", fmt.Errorf("iosbundle: clean %s: %w", projectDir, err)
	}
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		return "", err
	}

	subs := map[string]string{
		"__MAR_APP_NAME__":          swiftName,
		"__MAR_BUNDLE_ID__":         spec.BundleID,
		"__MAR_DISPLAY_NAME__":      spec.DisplayName,
		"__MAR_MARKETING_VERSION__": spec.MarketingVersion,
		"__MAR_BUILD_NUMBER__":      spec.BuildNumber,
		"__MAR_DEFAULT_BASE_URL__":  spec.DefaultBaseURL,
	}

	// One header per Swift file, stamped with the generator version
	// + a UTC timestamp. Stops people from editing the scaffold by
	// hand and losing their changes on the next `mar build --target ios`.
	// "DO NOT EDIT" is uppercased on purpose — the line is the loudest
	// signal in the file, and lowercase would read as polite advice
	// rather than the contract it actually is.
	marVersion := strings.TrimSpace(spec.MarVersion)
	if marVersion == "" {
		marVersion = "dev"
	}
	generatedAt := time.Now().UTC().Format("2006-01-02 15:04 UTC")
	swiftHeader := fmt.Sprintf(
		"// Generated by Mar (%s) on %s.\n"+
			"// This file is overwritten by `mar build --target ios`.\n"+
			"// DO NOT EDIT THIS FILE MANUALLY.\n\n",
		marVersion, generatedAt,
	)

	walkErr := fs.WalkDir(templateFS, "template", func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if path == "template" {
			return nil
		}
		rel := strings.TrimPrefix(path, "template/")
		// project.yml is the xcodegen input that lives in the embedded
		// template (so `make build` can regenerate the .xcodeproj),
		// but end users don't need it — the .xcodeproj is already
		// materialized. Skipping keeps the user's output minimal and
		// avoids implying that they should run xcodegen themselves.
		if rel == "project.yml" {
			return nil
		}
		// Substitute placeholders in the path itself, not just in
		// the file content. The .xcodeproj directory is named
		// "__MAR_APP_NAME__.xcodeproj" in the template; this is what
		// renames it to "<AppName>.xcodeproj" in the user's output.
		destRel := applySubstitutions(rel, subs)
		dest := filepath.Join(projectDir, destRel)
		if d.IsDir() {
			return os.MkdirAll(dest, 0o755)
		}
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			return err
		}
		raw, err := templateFS.ReadFile(path)
		if err != nil {
			return err
		}
		out := applySubstitutions(string(raw), subs)
		if filepath.Ext(dest) == ".swift" {
			out = swiftHeader + out
		}
		return os.WriteFile(dest, []byte(out), 0o644)
	})
	if walkErr != nil {
		return "", walkErr
	}

	// Embed the compiled program.json so the iOS shell paints its
	// first frame from this snapshot at cold-start (Approach C).
	// The Swift loader (MarLoader) reads from Bundle.main; the
	// pre-generated .pbxproj declares Resources/ as a folder
	// reference in the build phase.
	if len(spec.EmbeddedProgram) > 0 {
		resDir := filepath.Join(projectDir, "Resources")
		if err := os.MkdirAll(resDir, 0o755); err != nil {
			return "", fmt.Errorf("iosbundle: create Resources dir: %w", err)
		}
		progPath := filepath.Join(resDir, "program.json")
		if err := os.WriteFile(progPath, spec.EmbeddedProgram, 0o644); err != nil {
			return "", fmt.Errorf("iosbundle: write embedded program.json: %w", err)
		}
	}

	return projectDir, nil
}

func applySubstitutions(s string, subs map[string]string) string {
	for k, v := range subs {
		s = strings.ReplaceAll(s, k, v)
	}
	return s
}

// SwiftIdentifier turns an arbitrary string into a valid Swift
// identifier suitable for type names and target names. Strips
// non-alphanumeric characters, capitalizes word boundaries, and
// prefixes a leading digit with "App".
//
// Examples:
//
//	"notes-fullstack"  -> "NotesFullstack"
//	"my app v2"        -> "MyAppV2"
//	"123demo"          -> "App123demo"
//	""                 -> ""
func SwiftIdentifier(name string) string {
	if name == "" {
		return ""
	}
	parts := nonAlphaNumericRE.Split(name, -1)
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		// Title-case the first letter so multi-word names read like
		// CamelCase Swift types.
		b.WriteString(strings.ToUpper(p[:1]))
		if len(p) > 1 {
			b.WriteString(p[1:])
		}
	}
	id := b.String()
	if id == "" {
		return ""
	}
	// Swift identifiers cannot start with a digit.
	if id[0] >= '0' && id[0] <= '9' {
		id = "App" + id
	}
	return id
}

var nonAlphaNumericRE = regexp.MustCompile(`[^A-Za-z0-9]+`)
