// Package iosbundle materializes a generated Xcode project from an
// embedded template, substituting per-app config (display name, bundle
// id, baseURL).
//
// The Swift code is intentionally generic: it discovers what the mar
// backend exposes via /_mar/schema on cold start and renders generic
// UI for it. The "build" only needs to bake three things into the
// scaffold:
//
//   - app display name → Info.plist + project.yml + @main struct name
//   - bundle id        → project.yml
//   - default base URL → Info.plist (overridable at runtime in Settings)
//
// Output layout under outDir:
//
//	__MAR_APP_NAME__/
//	  project.yml             ← XcodeGen spec, run `xcodegen generate`
//	  Info.plist
//	  README.generated.md
//	  Sources/
//	    MarRuntimeIOSApp.swift
//	    AppViewModel.swift
//	    APIClient.swift
//	    Models.swift
//	    ContentView.swift
//	    ServicesTab.swift
//	    RoutesTab.swift
//	    SettingsTab.swift
//
// The user runs `xcodegen generate` to produce the .xcodeproj, opens
// it in Xcode, signs, and builds. From then on, any changes to the
// mar backend show up in the app on cold start without any iOS rebuild.
package iosbundle

import (
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"
)

//go:embed all:template
var templateFS embed.FS

// Spec is the per-app config baked into the generated project.
type Spec struct {
	// AppName is the human-readable display name shown on the home
	// screen and in the navigation bars. Also used as the Swift @main
	// struct name (via SwiftIdentifier). Must produce a valid Swift
	// identifier when stripped to alphanumerics — caller's
	// responsibility to validate (Generate sanitizes for safety).
	AppName string

	// BundleID is the iOS bundle identifier (reverse-DNS). Goes into
	// project.yml. Defaults derived from AppName if empty.
	BundleID string

	// DefaultBaseURL is baked into Info.plist as the initial value of
	// MarBaseURL. The user can override at runtime in Settings.
	DefaultBaseURL string

	// MarVersion is stamped into the per-file Swift header so anyone
	// looking at the generated code knows which `mar` produced it
	// (and that hand-editing won't survive the next build). Empty =
	// "dev" (matches cmd/mar/main.go's fallback).
	MarVersion string

	// EmbeddedProgram is the compiled program.json bytes for the
	// user's app. Written to Resources/program.json in the generated
	// project; the Swift loader reads it synchronously at cold-start
	// so the first frame paints instantly even before the network
	// fetch returns. Empty = embedded fallback omitted (Swift falls
	// back to fetching only).
	EmbeddedProgram []byte
}

// Generate writes the substituted template to outDir/<AppName>/. Any
// existing contents at that path are overwritten (the iOS scaffold is
// always considered disposable).
func Generate(spec Spec, outDir string) (projectDir string, err error) {
	if spec.AppName == "" {
		return "", fmt.Errorf("iosbundle: AppName is required")
	}
	swiftName := SwiftIdentifier(spec.AppName)
	if swiftName == "" {
		return "", fmt.Errorf("iosbundle: AppName %q has no valid Swift-identifier characters", spec.AppName)
	}
	if spec.BundleID == "" {
		spec.BundleID = "com.marlanghq." + strings.ToLower(swiftName)
	}
	if spec.DefaultBaseURL == "" {
		spec.DefaultBaseURL = "http://localhost:3000"
	}

	projectDir = filepath.Join(outDir, swiftName)
	if err := os.RemoveAll(projectDir); err != nil {
		return "", fmt.Errorf("iosbundle: clean %s: %w", projectDir, err)
	}
	if err := os.MkdirAll(projectDir, 0o755); err != nil {
		return "", err
	}

	subs := map[string]string{
		"__MAR_APP_NAME__":         swiftName,
		"__MAR_BUNDLE_ID__":        spec.BundleID,
		"__MAR_DEFAULT_BASE_URL__": spec.DefaultBaseURL,
	}

	// One header per Swift file, stamped with the generator version
	// + a UTC timestamp. Stops people from editing the scaffold by
	// hand and losing their changes on the next `mar build --target ios`.
	marVersion := strings.TrimSpace(spec.MarVersion)
	if marVersion == "" {
		marVersion = "dev"
	}
	generatedAt := time.Now().UTC().Format("2006-01-02 15:04 UTC")
	swiftHeader := fmt.Sprintf(
		"// Generated by Mar %s on %s.\n"+
			"// This file is overwritten by `mar build --target ios`.\n"+
			"// Do not edit this file manually.\n\n",
		marVersion, generatedAt,
	)

	walkErr := fs.WalkDir(templateFS, "template", func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if path == "template" {
			return nil
		}
		rel := strings.TrimPrefix(path, "template/")
		dest := filepath.Join(projectDir, rel)
		if d.IsDir() {
			return os.MkdirAll(dest, 0o755)
		}
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			return err
		}
		raw, err := templateFS.ReadFile(path)
		if err != nil {
			return err
		}
		out := applySubstitutions(string(raw), subs)
		// Swift sources get the "do not edit" preamble. Other files
		// (Info.plist, project.yml, README) stay as-is — they're
		// either XML/YAML/Markdown where comment syntax differs, or
		// already self-evidently generated.
		if filepath.Ext(dest) == ".swift" {
			out = swiftHeader + out
		}
		return os.WriteFile(dest, []byte(out), 0o644)
	})
	if walkErr != nil {
		return "", walkErr
	}

	// Embed the compiled program.json so the iOS shell paints its
	// first frame from this snapshot at cold-start (Approach C).
	// The Swift loader (MarLoader) reads from Bundle.main; project.yml
	// pulls Resources/ into the build phase as a folder reference.
	if len(spec.EmbeddedProgram) > 0 {
		resDir := filepath.Join(projectDir, "Resources")
		if err := os.MkdirAll(resDir, 0o755); err != nil {
			return "", fmt.Errorf("iosbundle: create Resources dir: %w", err)
		}
		progPath := filepath.Join(resDir, "program.json")
		if err := os.WriteFile(progPath, spec.EmbeddedProgram, 0o644); err != nil {
			return "", fmt.Errorf("iosbundle: write embedded program.json: %w", err)
		}
	}

	return projectDir, nil
}

func applySubstitutions(s string, subs map[string]string) string {
	for k, v := range subs {
		s = strings.ReplaceAll(s, k, v)
	}
	return s
}

// SwiftIdentifier turns an arbitrary string into a valid Swift
// identifier suitable for type names and target names. Strips
// non-alphanumeric characters, capitalizes word boundaries, and
// prefixes a leading digit with "App".
//
// Examples:
//
//	"notes-fullstack"  -> "NotesFullstack"
//	"my app v2"        -> "MyAppV2"
//	"123demo"          -> "App123demo"
//	""                 -> ""
func SwiftIdentifier(name string) string {
	if name == "" {
		return ""
	}
	parts := nonAlphaNumericRE.Split(name, -1)
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		// Title-case the first letter so multi-word names read like
		// CamelCase Swift types.
		b.WriteString(strings.ToUpper(p[:1]))
		if len(p) > 1 {
			b.WriteString(p[1:])
		}
	}
	id := b.String()
	if id == "" {
		return ""
	}
	// Swift identifiers cannot start with a digit.
	if id[0] >= '0' && id[0] <= '9' {
		id = "App" + id
	}
	return id
}

var nonAlphaNumericRE = regexp.MustCompile(`[^A-Za-z0-9]+`)
