package cli

import (
	"bufio"
	"encoding/json"
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"time"

	"mar/internal/model"
)

//go:embed ios_template/.swiftlint.yml ios_template/Info.plist ios_template/MarRuntimeIOS.xcodeproj/project.pbxproj ios_template/MarRuntimeIOS.xcodeproj/project.xcworkspace/contents.xcworkspacedata ios_template/Sources/*.swift
var iosTemplateFS embed.FS

const iosGeneratedReadme = `# Generated iOS project

This project was generated by Mar.

Next steps:

1. Open MarRuntimeIOS.xcodeproj in Xcode on macOS.
2. Select your signing team in Xcode.
3. Build and run on an iPhone, iPad, or Simulator.
`

func runIOS(binaryName string, args []string) error {
	if len(args) == 0 {
		return iosUsageError(binaryName)
	}

	switch args[0] {
	case "generate":
		return runIOSGenerate(binaryName, args[1:])
	default:
		return iosUsageError(binaryName)
	}
}

func runIOSGenerate(binaryName string, args []string) error {
	if len(args) != 1 && len(args) != 2 {
		return iosUsageError(binaryName)
	}

	app, err := parseMarFile(args[0])
	if err != nil {
		return err
	}
	printAppWarnings(app)

	if app.IOS == nil {
		return iosMissingConfigError(args[0], app.AppName)
	}

	outputDir := defaultIOSOutputDir(args[0], "")
	if len(args) == 2 {
		outputDir = args[1]
	}

	if err := ensureSafeIOSOutputDir(outputDir); err != nil {
		return err
	}
	confirmed, err := confirmIOSGenerateRecreate(outputDir)
	if err != nil {
		return err
	}
	if !confirmed {
		return nil
	}
	if err := os.RemoveAll(outputDir); err != nil {
		return err
	}
	if err := generateIOSProject(binaryName, app, outputDir); err != nil {
		return err
	}

	printIOSGenerateSummary(outputDir)
	return nil
}

func iosUsageError(binaryName string) error {
	useColor := cliSupportsANSIStream(os.Stderr)
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n", colorizeCLI(useColor, "\033[1;31m", "iOS usage"))
	fmt.Fprintf(&b, "  %s\n", fmt.Sprintf("%s ios generate <app.mar> [output-dir]", binaryName))
	fmt.Fprintf(&b, "\n%s\n", colorizeCLI(useColor, "\033[1;33m", "Hint:"))
	fmt.Fprintf(&b, "  Generate a fresh iOS project with: %s\n", colorizeCLI(useColor, "\033[1;32m", fmt.Sprintf("%s ios generate app.mar", binaryName)))
	return styledCLIError(strings.TrimRight(b.String(), "\n") + "\n")
}

func iosMissingConfigError(path string, appName string) error {
	useColor := cliSupportsANSIStream(os.Stderr)
	highlightValue := func(value string) string {
		return colorizeCLI(useColor, "\033[36m", value)
	}
	exampleName := iosExampleName(appName)

	var b strings.Builder
	fmt.Fprintf(&b, "%s\n", colorizeCLI(useColor, "\033[1;31m", "iOS generation error"))
	fmt.Fprintf(
		&b,
		"  ios.generate requires an ios block with %s and %s in %s\n",
		highlightValue("bundle_identifier"),
		highlightValue("server_url"),
		highlightValue(path),
	)
	fmt.Fprintf(&b, "\n%s\n", colorizeCLI(useColor, "\033[1;33m", "Hint:"))
	fmt.Fprintf(&b, "  Add an %s block like:\n", colorizeCLI(useColor, "\033[1m", "ios"))
	fmt.Fprintf(&b, "    %s {\n", colorizeCLI(useColor, "\033[1m", "ios"))
	fmt.Fprintf(&b, "      bundle_identifier %s\n", highlightValue(`"com.example.`+exampleName+`"`))
	fmt.Fprintf(&b, "      server_url %s\n", highlightValue(`"https://`+exampleName+`.example.com"`))
	fmt.Fprintf(&b, "    }\n")
	return styledCLIError(strings.TrimRight(b.String(), "\n") + "\n")
}

func iosExampleName(appName string) string {
	var b strings.Builder
	for _, r := range appName {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
			if r >= 'A' && r <= 'Z' {
				r = r + ('a' - 'A')
			}
			b.WriteRune(r)
		}
	}
	if b.Len() == 0 {
		return "app"
	}
	return b.String()
}

func printIOSGenerateSummary(outputDir string) {
	useColor := cliSupportsANSIStream(os.Stdout)
	projectPath := filepath.ToSlash(filepath.Join(outputDir, "MarRuntimeIOS.xcodeproj"))

	fmt.Printf("\n%s\n", colorizeCLI(useColor, "\033[1;32m", "iOS project ready"))
	fmt.Printf("  %s\n", filepath.ToSlash(outputDir))
	fmt.Println()
	fmt.Printf("%s\n", colorizeCLI(useColor, "\033[1;33m", "Next steps"))
	fmt.Printf("  1. On %s, open the Xcode project: %s\n", colorizeCLI(useColor, "\033[1m", "macOS"), colorizeCLI(useColor, "\033[1;32m", "open "+projectPath))
	fmt.Printf("  2. Select your %s.\n", colorizeCLI(useColor, "\033[1m", "signing team"))
	fmt.Printf("  3. Build and run on an iPhone, iPad, or Simulator.\n")
	fmt.Println()
}

func defaultIOSOutputDir(inputPath, override string) string {
	if trimmed := strings.TrimSpace(override); trimmed != "" {
		return trimmed
	}
	base := filepath.Base(inputPath)
	base = strings.TrimSuffix(base, filepath.Ext(base))
	base = filepath.Base(base)
	if base == "" || base == "." {
		base = "app"
	}
	return filepath.Join("dist", base+"-ios")
}

func ensureSafeIOSOutputDir(outputDir string) error {
	cleaned := filepath.Clean(strings.TrimSpace(outputDir))
	if cleaned == "" || cleaned == "." || cleaned == string(filepath.Separator) {
		return fmt.Errorf("refusing to regenerate iOS project into %q", outputDir)
	}
	return nil
}

func confirmIOSGenerateRecreate(outputDir string) (bool, error) {
	if !iosOutputDirHasContents(outputDir) {
		return true, nil
	}
	if !stdinIsTerminal() {
		useColor := cliSupportsANSIStream(os.Stderr)
		coloredOutputDir := colorizeCLI(useColor, "\033[1;35m", filepath.ToSlash(outputDir))
		var b strings.Builder
		fmt.Fprintf(&b, "%s\n", colorizeCLI(useColor, "\033[1;31m", "iOS generate requires confirmation"))
		fmt.Fprintf(&b, "  %s already contains files.\n", coloredOutputDir)
		fmt.Fprintf(&b, "  %s\n", colorizeCLI(useColor, "\033[1;31m", "If you continue, that folder will be deleted and the iOS project will be generated again."))
		fmt.Fprintf(&b, "  %s\n", colorizeCLI(useColor, "\033[1;31m", "Any manual changes made inside it will be lost."))
		fmt.Fprintf(&b, "\n%s\n", colorizeCLI(useColor, "\033[1;33m", "Hint:"))
		fmt.Fprintf(&b, "  Re-run this command in an interactive terminal to confirm the overwrite.\n")
		return false, styledCLIError(strings.TrimRight(b.String(), "\n") + "\n")
	}

	useColor := cliSupportsANSIStream(os.Stdout)
	coloredOutputDir := colorizeCLI(useColor, "\033[1;35m", filepath.ToSlash(outputDir))
	fmt.Println()
	fmt.Printf("%s\n", colorizeCLI(useColor, "\033[1;33m", "iOS project already exists"))
	fmt.Printf("  %s already contains files.\n", coloredOutputDir)
	fmt.Println()
	fmt.Printf("  %s\n", colorizeCLI(useColor, "\033[1;31m", "If you continue, that folder will be deleted and the iOS project will be generated again."))
	fmt.Printf("  %s\n", colorizeCLI(useColor, "\033[1;31m", "Any manual changes made inside it will be lost."))
	fmt.Println()
	reader := bufio.NewReader(os.Stdin)
	confirmed, err := promptYesNo(reader, os.Stdout, useColor, "Continue? [y/N]", false)
	if err != nil {
		return false, err
	}
	if !confirmed {
		fmt.Println()
		fmt.Printf("%s\n\n", colorizeCLI(useColor, "\033[1;31m", "iOS generate canceled"))
		return false, nil
	}
	return true, nil
}

func iosOutputDirHasContents(path string) bool {
	entries, err := os.ReadDir(path)
	if err != nil {
		return false
	}
	return len(entries) > 0
}

func generateIOSProject(binaryName string, app *model.App, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return err
	}

	displayName := app.IOS.DisplayName
	if strings.TrimSpace(displayName) == "" {
		displayName = app.AppName
	}

	replacements := map[string]string{
		"__MAR_IOS_BUNDLE_IDENTIFIER__":                    app.IOS.BundleIdentifier,
		"__MAR_IOS_DISPLAY_NAME__":                         displayName,
		"<!-- __MAR_IOS_HTTP_APP_TRANSPORT_SECURITY__ -->": iosHTTPAppTransportSecurity(app.IOS.ServerURL),
		"__MAR_IOS_EMBEDDED_SCHEMA__":                      mustIOSEmbeddedSchemaJSON(app),
		"__MAR_IOS_SERVER_URL__":                           app.IOS.ServerURL,
	}
	marVersion := readVersionInfo(binaryName).Version
	generatedAt := time.Now().UTC().Format("2006-01-02 15:04 UTC")

	if err := fs.WalkDir(iosTemplateFS, "ios_template", func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if path == "ios_template" {
			return nil
		}

		relPath, err := filepath.Rel("ios_template", path)
		if err != nil {
			return err
		}
		targetPath := filepath.Join(outputDir, relPath)
		if d.IsDir() {
			return os.MkdirAll(targetPath, 0o755)
		}

		data, err := fs.ReadFile(iosTemplateFS, path)
		if err != nil {
			return err
		}
		content := string(data)
		for oldValue, newValue := range replacements {
			content = strings.ReplaceAll(content, oldValue, newValue)
		}
		if filepath.Ext(targetPath) == ".swift" {
			content = generatedSwiftFileHeader(marVersion, generatedAt) + content
		}
		return os.WriteFile(targetPath, []byte(content), 0o644)
	}); err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(outputDir, "README.generated.md"), []byte(iosGeneratedReadme), 0o644)
}

func mustIOSEmbeddedSchemaJSON(app *model.App) string {
	payload := map[string]any{
		"appName":  app.AppName,
		"port":     app.Port,
		"database": app.Database,
		"entities": app.Entities,
	}
	if app.Auth != nil {
		payload["auth"] = map[string]any{
			"enabled":        true,
			"userEntity":     app.Auth.UserEntity,
			"emailField":     app.Auth.EmailField,
			"roleField":      app.Auth.RoleField,
			"needsBootstrap": false,
		}
	}
	if len(app.InputAliases) > 0 {
		payload["inputAliases"] = app.InputAliases
	}
	if len(app.Actions) > 0 {
		actions := make([]map[string]any, 0, len(app.Actions))
		for _, action := range app.Actions {
			actions = append(actions, map[string]any{
				"name":       action.Name,
				"inputAlias": action.InputAlias,
				"steps":      len(action.Steps),
			})
		}
		payload["actions"] = actions
	}
	if app.Frontend != nil {
		payload["frontend"] = app.Frontend
	}
	data, err := json.Marshal(payload)
	if err != nil {
		return "{}"
	}
	return string(data)
}

func generatedSwiftFileHeader(marVersion, generatedAt string) string {
	return fmt.Sprintf(
		"// Generated by Mar %s on %s.\n// This file may be overwritten by `mar ios generate`.\n// Do not edit this file manually.\n\n",
		strings.TrimSpace(marVersion),
		strings.TrimSpace(generatedAt),
	)
}

func iosHTTPAppTransportSecurity(serverURL string) string {
	trimmed := strings.TrimSpace(strings.ToLower(serverURL))
	if !strings.HasPrefix(trimmed, "http://") {
		return ""
	}
	return "\t\t<key>NSAllowsArbitraryLoads</key>\n\t\t<true/>"
}
