package cli

import (
	"bufio"
	"embed"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"mar/internal/model"
)

//go:embed ios_template/**
var iosTemplateFS embed.FS

const iosGeneratedReadme = `# Generated iOS project

This project was generated by Mar.

Next steps:

1. Open MarRuntimeIOS.xcodeproj in Xcode on macOS.
2. Select your signing team in Xcode.
3. Build and run on an iPhone, iPad, or Simulator.
`

func runIOS(binaryName string, args []string) error {
	if len(args) == 0 {
		return iosUsageError(binaryName)
	}

	switch args[0] {
	case "generate":
		return runIOSGenerate(binaryName, args[1:])
	default:
		return iosUsageError(binaryName)
	}
}

func runIOSGenerate(binaryName string, args []string) error {
	if len(args) != 1 && len(args) != 2 {
		return iosUsageError(binaryName)
	}

	app, err := parseMarFile(args[0])
	if err != nil {
		return err
	}
	printAppWarnings(app)

	if app.IOS == nil {
		return iosMissingConfigError(args[0])
	}

	outputDir := defaultIOSOutputDir(args[0], "")
	if len(args) == 2 {
		outputDir = args[1]
	}

	if err := ensureSafeIOSOutputDir(outputDir); err != nil {
		return err
	}
	confirmed, err := confirmIOSGenerateRecreate(outputDir)
	if err != nil {
		return err
	}
	if !confirmed {
		return nil
	}
	if err := os.RemoveAll(outputDir); err != nil {
		return err
	}
	if err := generateIOSProject(app, outputDir); err != nil {
		return err
	}

	printIOSGenerateSummary(outputDir)
	return nil
}

func iosUsageError(binaryName string) error {
	useColor := cliSupportsANSIStream(os.Stderr)
	var b strings.Builder
	fmt.Fprintf(&b, "%s\n", colorizeCLI(useColor, "\033[1;31m", "iOS usage"))
	fmt.Fprintf(&b, "  %s\n", fmt.Sprintf("%s ios generate <app.mar> [output-dir]", binaryName))
	fmt.Fprintf(&b, "\n%s\n", colorizeCLI(useColor, "\033[1;33m", "Hint:"))
	fmt.Fprintf(&b, "  Generate a fresh iOS project with: %s\n", colorizeCLI(useColor, "\033[1;32m", fmt.Sprintf("%s ios generate app.mar", binaryName)))
	return styledCLIError(strings.TrimRight(b.String(), "\n") + "\n")
}

func iosMissingConfigError(path string) error {
	useColor := cliSupportsANSIStream(os.Stderr)
	highlightValue := func(value string) string {
		return colorizeCLI(useColor, "\033[36m", value)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "%s\n", colorizeCLI(useColor, "\033[1;31m", "iOS generation error"))
	fmt.Fprintf(
		&b,
		"  ios.generate requires an ios block with %s and %s in %s\n",
		highlightValue("bundle_identifier"),
		highlightValue("server_url"),
		highlightValue(path),
	)
	fmt.Fprintf(&b, "\n%s\n", colorizeCLI(useColor, "\033[1;33m", "Hint:"))
	fmt.Fprintf(&b, "  Add an %s block like:\n", colorizeCLI(useColor, "\033[1m", "ios"))
	fmt.Fprintf(&b, "    %s {\n", colorizeCLI(useColor, "\033[1m", "ios"))
	fmt.Fprintf(&b, "      bundle_identifier %s\n", highlightValue(`"com.example.school"`))
	fmt.Fprintf(&b, "      server_url %s\n", highlightValue(`"https://school.example.com"`))
	fmt.Fprintf(&b, "    }\n")
	return styledCLIError(strings.TrimRight(b.String(), "\n") + "\n")
}

func printIOSGenerateSummary(outputDir string) {
	useColor := cliSupportsANSIStream(os.Stdout)
	projectPath := filepath.ToSlash(filepath.Join(outputDir, "MarRuntimeIOS.xcodeproj"))

	fmt.Printf("\n%s\n", colorizeCLI(useColor, "\033[1;32m", "iOS project ready"))
	fmt.Printf("  %s\n", filepath.ToSlash(outputDir))
	fmt.Println()
	fmt.Printf("%s\n", colorizeCLI(useColor, "\033[1;33m", "Next steps"))
	fmt.Printf("  1. On %s, open the Xcode project: %s\n", colorizeCLI(useColor, "\033[1m", "macOS"), colorizeCLI(useColor, "\033[1;32m", "open "+projectPath))
	fmt.Printf("  2. Select your %s.\n", colorizeCLI(useColor, "\033[1m", "signing team"))
	fmt.Printf("  3. Build and run on an iPhone, iPad, or Simulator.\n")
	fmt.Println()
}

func defaultIOSOutputDir(inputPath, override string) string {
	if trimmed := strings.TrimSpace(override); trimmed != "" {
		return trimmed
	}
	base := filepath.Base(inputPath)
	base = strings.TrimSuffix(base, filepath.Ext(base))
	base = filepath.Base(base)
	if base == "" || base == "." {
		base = "app"
	}
	return filepath.Join("dist", base+"-ios")
}

func ensureSafeIOSOutputDir(outputDir string) error {
	cleaned := filepath.Clean(strings.TrimSpace(outputDir))
	if cleaned == "" || cleaned == "." || cleaned == string(filepath.Separator) {
		return fmt.Errorf("refusing to regenerate iOS project into %q", outputDir)
	}
	return nil
}

func confirmIOSGenerateRecreate(outputDir string) (bool, error) {
	if !iosOutputDirHasContents(outputDir) {
		return true, nil
	}
	if !stdinIsTerminal() {
		useColor := cliSupportsANSIStream(os.Stderr)
		coloredOutputDir := colorizeCLI(useColor, "\033[1;35m", filepath.ToSlash(outputDir))
		var b strings.Builder
		fmt.Fprintf(&b, "%s\n", colorizeCLI(useColor, "\033[1;31m", "iOS generate requires confirmation"))
		fmt.Fprintf(&b, "  %s already contains files.\n", coloredOutputDir)
		fmt.Fprintf(&b, "  %s\n", colorizeCLI(useColor, "\033[1;31m", "If you continue, that folder will be deleted and the iOS project will be generated again."))
		fmt.Fprintf(&b, "  %s\n", colorizeCLI(useColor, "\033[1;31m", "Any manual changes made inside it will be lost."))
		fmt.Fprintf(&b, "\n%s\n", colorizeCLI(useColor, "\033[1;33m", "Hint:"))
		fmt.Fprintf(&b, "  Re-run this command in an interactive terminal to confirm the overwrite.\n")
		return false, styledCLIError(strings.TrimRight(b.String(), "\n") + "\n")
	}

	useColor := cliSupportsANSIStream(os.Stdout)
	coloredOutputDir := colorizeCLI(useColor, "\033[1;35m", filepath.ToSlash(outputDir))
	fmt.Println()
	fmt.Printf("%s\n", colorizeCLI(useColor, "\033[1;33m", "iOS project already exists"))
	fmt.Printf("  %s already contains files.\n", coloredOutputDir)
	fmt.Println()
	fmt.Printf("  %s\n", colorizeCLI(useColor, "\033[1;31m", "If you continue, that folder will be deleted and the iOS project will be generated again."))
	fmt.Printf("  %s\n", colorizeCLI(useColor, "\033[1;31m", "Any manual changes made inside it will be lost."))
	fmt.Println()
	reader := bufio.NewReader(os.Stdin)
	confirmed, err := promptYesNo(reader, os.Stdout, useColor, "Continue? [y/N]", false)
	if err != nil {
		return false, err
	}
	if !confirmed {
		fmt.Println()
		fmt.Printf("%s\n\n", colorizeCLI(useColor, "\033[1;31m", "iOS generate canceled"))
		return false, nil
	}
	return true, nil
}

func iosOutputDirHasContents(path string) bool {
	entries, err := os.ReadDir(path)
	if err != nil {
		return false
	}
	return len(entries) > 0
}

func generateIOSProject(app *model.App, outputDir string) error {
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return err
	}

	displayName := app.IOS.DisplayName
	if strings.TrimSpace(displayName) == "" {
		displayName = app.AppName
	}

	replacements := map[string]string{
		"__MAR_IOS_BUNDLE_IDENTIFIER__": app.IOS.BundleIdentifier,
		"__MAR_IOS_DISPLAY_NAME__":      displayName,
		"__MAR_IOS_SERVER_URL__":        app.IOS.ServerURL,
	}

	if err := fs.WalkDir(iosTemplateFS, "ios_template", func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if path == "ios_template" {
			return nil
		}

		relPath, err := filepath.Rel("ios_template", path)
		if err != nil {
			return err
		}
		targetPath := filepath.Join(outputDir, relPath)
		if d.IsDir() {
			return os.MkdirAll(targetPath, 0o755)
		}

		data, err := fs.ReadFile(iosTemplateFS, path)
		if err != nil {
			return err
		}
		content := string(data)
		for oldValue, newValue := range replacements {
			content = strings.ReplaceAll(content, oldValue, newValue)
		}
		return os.WriteFile(targetPath, []byte(content), 0o644)
	}); err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(outputDir, "README.generated.md"), []byte(iosGeneratedReadme), 0o644)
}
