// Package ctorgen derives the runtime registrations of every QUALIFIED
// builtin union constructor (Canvas.Translate, Keyboard.KeyW, Sound.Square,
// ...) from the one table that already owns them: the typecheck package's
// builtin CustomTypes, selected by their Module field.
//
// Before this existed, each runtime hand-registered its own copy of the set
// (and the JS runtime skipped Keyboard/Gamepad/Auth entirely, leaning on an
// eval-time fallback), so a constructor could exist in one runtime and not
// another with no test noticing — proven by deleting Canvas.Multiply from the
// Swift bundle and watching the whole suite stay green (2026-07-15). Now the
// generator emits the registrations as LITERAL source (visible to the
// regex-based drift tests) into:
//
//   - internal/jsserve/runtime.js               (a marked region)
//   - internal/iosbundle/template/Sources/MarBuiltinCtors.swift (whole file)
//
// and the staleness test in this package fails whenever the committed output
// disagrees with the table. To change the set: edit the union in typecheck
// (env.go / keyboard.go / gamepad.go / sound.go), then run
//
//	go generate ./internal/ctorgen
//
//go:generate go run ./cmd
package ctorgen

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"mar/internal/typecheck"
)

// Entry is one qualified constructor: Canvas.Blend = VCtor("Blend")/1.
type Entry struct {
	Qualified string // the env key, e.g. "Keyboard.KeyW"
	Tag       string // the bare runtime tag, e.g. "KeyW"
	Arity     int
}

// Entries returns every constructor of every builtin union whose Module is
// set, in a deterministic order (unions sorted by name, constructors in
// declaration order). It panics on a duplicate qualified name — two unions
// under the same module must not share a constructor name.
func Entries() []Entry {
	customs := typecheck.BaseCustomTypes()
	unions := make([]string, 0, len(customs))
	for name, ct := range customs {
		if ct.Module != "" {
			unions = append(unions, name)
		}
	}
	sort.Strings(unions)

	seen := map[string]string{}
	var out []Entry
	for _, name := range unions {
		ct := customs[name]
		if len(ct.CtorOrder) == 0 {
			panic(fmt.Sprintf("ctorgen: builtin union %q has Module %q but no CtorOrder", name, ct.Module))
		}
		for _, ctor := range ct.CtorOrder {
			q := ct.Module + "." + ctor
			if prev, dup := seen[q]; dup {
				panic(fmt.Sprintf("ctorgen: %q declared by both %q and %q", q, prev, name))
			}
			seen[q] = name
			out = append(out, Entry{Qualified: q, Tag: ctor, Arity: len(ct.Constructors[ctor].Args)})
		}
	}
	return out
}

// JS region markers in internal/jsserve/runtime.js. The generator replaces
// everything between them; the lines themselves stay.
const (
	JSBegin = "    // BEGIN GENERATED BUILTIN CTORS (go generate ./internal/ctorgen) — DO NOT EDIT"
	JSEnd   = "    // END GENERATED BUILTIN CTORS"
)

// JSRegion renders the full marked region for runtime.js, markers included.
func JSRegion() string {
	var b strings.Builder
	b.WriteString(JSBegin + "\n")
	b.WriteString("    // Every qualified builtin union constructor, straight from the\n")
	b.WriteString("    // typecheck tables (CustomType.Module). Nothing here is hand-picked:\n")
	b.WriteString("    // if a name is missing, fix the union in typecheck and regenerate.\n")
	for _, e := range Entries() {
		if e.Arity == 0 {
			fmt.Fprintf(&b, "    def('%s', VCtor('%s'));\n", e.Qualified, e.Tag)
		} else {
			fmt.Fprintf(&b, "    def('%s', native(%d, args => VCtor('%s', args.slice())));\n", e.Qualified, e.Arity, e.Tag)
		}
	}
	b.WriteString(JSEnd)
	return b.String()
}

// SwiftFile renders the entire MarBuiltinCtors.swift.
func SwiftFile() string {
	var b strings.Builder
	b.WriteString("// Code generated by internal/ctorgen; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Every qualified builtin union constructor (Canvas.Translate,\n")
	b.WriteString("// Keyboard.KeyW, Sound.Square, ...), derived from the typecheck package's\n")
	b.WriteString("// union tables (CustomType.Module). Literal env.define calls on purpose:\n")
	b.WriteString("// the drift tests read this file with a regex, and the staleness test in\n")
	b.WriteString("// internal/ctorgen fails whenever it disagrees with the tables. To change\n")
	b.WriteString("// the set, edit the union in typecheck and run: go generate ./internal/ctorgen\n\n")
	b.WriteString("enum MarBuiltinCtors {\n")
	b.WriteString("    static func register(_ env: Env) {\n")
	for _, e := range Entries() {
		if e.Arity == 0 {
			fmt.Fprintf(&b, "        env.define(\"%s\", .ctor(tag: \"%s\", args: [], origin: nil))\n", e.Qualified, e.Tag)
		} else {
			fmt.Fprintf(&b, "        env.define(\"%s\", .fn(MarFn.native(%d) { .ctor(tag: \"%s\", args: $0, origin: nil) }))\n", e.Qualified, e.Arity, e.Tag)
		}
	}
	b.WriteString("    }\n")
	b.WriteString("}\n")
	return b.String()
}

// GoFile renders the entire internal/runtime/builtin_ctors_gen.go.
//
// The Go runtime was the last one still hand-registering this set, which is
// exactly the state the package comment describes as the reason this generator
// exists — and it had the same consequence. `Keyboard.*` and `Gamepad.*` were
// registered in the JS and Swift runtimes and nowhere in Go, so a shared module
// holding something as ordinary as
//
//	jumpKey : Keyboard.Key
//	jumpKey = Keyboard.Space
//
// passed `mar check` and then killed the server at boot with
// `unbound constructor: Keyboard.Space`. A constructor is data; which side
// evaluates it is not its business. Generating all three from the one table
// makes "present in one runtime, missing in another" unrepresentable.
func GoFile() string {
	var b strings.Builder
	b.WriteString("// Code generated by internal/ctorgen; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Every qualified builtin union constructor (Canvas.Translate,\n")
	b.WriteString("// Keyboard.KeyW, Sound.Square, ...), derived from the typecheck package's\n")
	b.WriteString("// union tables (CustomType.Module). To change the set, edit the union in\n")
	b.WriteString("// typecheck and run: go generate ./internal/ctorgen\n\n")
	b.WriteString("package runtime\n\n")
	b.WriteString("func builtinCtors() map[string]Value {\n")
	b.WriteString("\treturn map[string]Value{\n")
	for _, e := range Entries() {
		if e.Arity == 0 {
			fmt.Fprintf(&b, "\t\t%q: VCtor{Tag: %q},\n", e.Qualified, e.Tag)
		} else {
			fmt.Fprintf(&b, "\t\t%q: nativeFn(%d, func(args []Value) (Value, error) {\n", e.Qualified, e.Arity)
			fmt.Fprintf(&b, "\t\t\treturn VCtor{Tag: %q, Args: append([]Value(nil), args...)}, nil\n", e.Tag)
			b.WriteString("\t\t}),\n")
		}
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	// Run it through gofmt so the committed file is canonical and the
	// repo-wide `gofmt -l` check and the staleness test agree on one spelling.
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		panic(fmt.Sprintf("ctorgen: generated Go does not parse: %v", err))
	}
	return string(formatted)
}

// SpliceJS returns src with the marked region replaced by the current
// JSRegion. It errors if the markers are missing or out of order.
func SpliceJS(src string) (string, error) {
	begin := strings.Index(src, JSBegin)
	end := strings.Index(src, JSEnd)
	if begin < 0 || end < 0 || end < begin {
		return "", fmt.Errorf("ctorgen: BEGIN/END GENERATED BUILTIN CTORS markers not found (or reversed) in runtime.js")
	}
	return src[:begin] + JSRegion() + src[end+len(JSEnd):], nil
}
