package auth

import (
	"fmt"
	"net/smtp"
	"os"
	"strings"
	"unicode/utf8"
)

// Email is the message the runtime asks the mailer to send. From is
// taken from Auth.config; To is the user's email. Subject is from
// Auth.config; Body is generated by the framework with the code.
type Email struct {
	From    string
	To      string
	Subject string
	Body    string
}

// SMTPConfig mirrors the mar.json `mail` block. When Host is empty the
// stdout sink is used (see Send below).
type SMTPConfig struct {
	Host     string
	Port     int
	Username string
	Password string
}

// Send delivers the email — via SMTP if `cfg.Host` is set, otherwise
// to stdout (so `mar dev` works without any SMTP setup; the developer
// can grab the code from the terminal).
func Send(cfg SMTPConfig, msg Email) error {
	if cfg.Host == "" {
		writeStdoutSink(msg)
		return nil
	}
	addr := fmt.Sprintf("%s:%d", cfg.Host, cfg.Port)
	wire := buildWireMessage(msg)
	var auth smtp.Auth
	if cfg.Username != "" {
		auth = smtp.PlainAuth("", cfg.Username, cfg.Password, cfg.Host)
	}
	if err := smtp.SendMail(addr, auth, msg.From, []string{msg.To}, []byte(wire)); err != nil {
		return fmt.Errorf("auth.Send: smtp: %w", err)
	}
	return nil
}

// buildWireMessage formats the email per RFC 5322 with the headers
// SMTP servers expect. Plain text only; if rich HTML is ever needed it
// goes through a separate constructor.
func buildWireMessage(msg Email) string {
	var b strings.Builder
	b.WriteString("From: ")
	b.WriteString(msg.From)
	b.WriteString("\r\n")
	b.WriteString("To: ")
	b.WriteString(msg.To)
	b.WriteString("\r\n")
	b.WriteString("Subject: ")
	b.WriteString(msg.Subject)
	b.WriteString("\r\n")
	b.WriteString("MIME-Version: 1.0\r\n")
	b.WriteString("Content-Type: text/plain; charset=UTF-8\r\n")
	b.WriteString("\r\n")
	b.WriteString(msg.Body)
	return b.String()
}

// writeStdoutSink prints the email with a header rule that names the
// sink, the From/To/Subject metadata indented, and the body indented
// underneath. A bottom rule closes the block so multiple sign-in
// attempts in a row stay visually distinguishable.
//
// The rules and label render in dim ANSI on a TTY; CI / NO_COLOR
// environments get plain ASCII.
func writeStdoutSink(msg Email) {
	const width = 60
	tty := isStdoutTerminal()
	dim := wrap(tty, "\x1b[2m", "\x1b[0m")

	const label = "[mar auth] outgoing email (no SMTP configured)"
	prefix := "─── " + label + " "
	if pad := width - utf8.RuneCountInString(prefix); pad > 0 {
		prefix += strings.Repeat("─", pad)
	}
	fmt.Fprintln(os.Stdout, dim(prefix))

	fmt.Fprintf(os.Stdout, "  %s    %s\n", dim("From:"), msg.From)
	fmt.Fprintf(os.Stdout, "  %s      %s\n", dim("To:"), msg.To)
	fmt.Fprintf(os.Stdout, "  %s %s\n", dim("Subject:"), msg.Subject)
	fmt.Fprintln(os.Stdout)

	body := strings.TrimRight(msg.Body, "\n\r ")
	for _, line := range strings.Split(body, "\n") {
		if line == "" {
			fmt.Fprintln(os.Stdout)
		} else {
			fmt.Fprintf(os.Stdout, "  %s\n", line)
		}
	}

	fmt.Fprintln(os.Stdout, dim(strings.Repeat("─", width)))
	fmt.Fprintln(os.Stdout)
}

func isStdoutTerminal() bool {
	if os.Getenv("NO_COLOR") != "" {
		return false
	}
	fi, err := os.Stdout.Stat()
	return err == nil && (fi.Mode()&os.ModeCharDevice) != 0
}

func wrap(active bool, prefix, suffix string) func(string) string {
	if !active {
		return func(s string) string { return s }
	}
	return func(s string) string { return prefix + s + suffix }
}

// DefaultBody returns the framework's default email body. Subject
// carries the app's brand; body stays generic and transactional.
func DefaultBody(code string, ttlMinutes int) string {
	return fmt.Sprintf(
		"Your sign-in code is %s.\n\nIt expires in %d minutes. "+
			"If you didn't request this, you can ignore this email.\n",
		code, ttlMinutes,
	)
}
