package auth

import (
	"fmt"
	"net/smtp"
	"os"
	"strings"
	"unicode/utf8"
)

// Email is the message the runtime asks the mailer to send. From is
// taken from Auth.config; To is the user's email. Subject is from
// Auth.config; Body is generated by the framework with the code.
type Email struct {
	From    string
	To      string
	Subject string
	Body    string
}

// SMTPConfig mirrors the mar.json `mail` block, plus one field that does
// not come from the manifest: AllowStdoutSink.
type SMTPConfig struct {
	Host     string
	Port     int
	Username string
	Password string

	// AllowStdoutSink permits Send to print the email (sign-in CODE
	// included) to stdout when SMTP is incomplete. It is the dev-server
	// convenience that lets `mar dev` work with zero mail setup.
	//
	// It defaults to FALSE on purpose, and only `mar dev` sets it. In
	// production stdout is the log stream: Fly, journald and friends
	// capture it, so printing there means anyone who can read the logs
	// can read a valid one-time code. Security audit 2026-07-15, finding
	// #6: an admin-only project could boot without SMTP and leak admin
	// OTPs into production logs.
	//
	// A zero-value SMTPConfig is therefore safe by construction: a new
	// caller that forgets this field gets the refusal, not the leak.
	AllowStdoutSink bool
}

// Complete reports whether the config can actually authenticate against
// a provider. Both Host AND Password are needed: providers (Resend,
// SendGrid, …) reject anonymous SMTP, so a bare Host cannot deliver.
// This is the single definition of "SMTP is usable": Send routes on it
// and the boot guard checks it, so the two can never disagree.
func (c SMTPConfig) Complete() bool {
	return c.Host != "" && c.Password != ""
}

// Send delivers the email via SMTP when the config is complete.
//
// When it is not complete there are two outcomes, and which one you get
// is decided by cfg.AllowStdoutSink, never inferred:
//
//   - allowed (`mar dev`): print to stdout, so the developer can grab
//     the code from the terminal with no mail setup at all. `mar dev`
//     also lands here when the operator used an `env:SMTP_PASSWORD` ref
//     but never exported the variable.
//   - not allowed (production): return an error WITHOUT printing. The
//     sign-in request fails loudly instead of quietly writing a valid
//     one-time code into the log stream.
//
// In practice production never reaches the second case, because
// ServeLive refuses to boot when a mail-sending surface is mounted with
// incomplete SMTP. This is the backstop for any future path that skips
// that check.
func Send(cfg SMTPConfig, msg Email) error {
	if !cfg.Complete() {
		if !cfg.AllowStdoutSink {
			return fmt.Errorf(
				"auth.Send: refusing to deliver a sign-in code with no SMTP configured " +
					"(printing it would write the code to the log stream); " +
					"set mail.smtpHost and mail.smtpPassword in mar.json")
		}
		writeStdoutSink(msg)
		return nil
	}
	addr := fmt.Sprintf("%s:%d", cfg.Host, cfg.Port)
	wire := buildWireMessage(msg)
	var auth smtp.Auth
	if cfg.Username != "" {
		auth = smtp.PlainAuth("", cfg.Username, cfg.Password, cfg.Host)
	}
	if err := smtp.SendMail(addr, auth, msg.From, []string{msg.To}, []byte(wire)); err != nil {
		return fmt.Errorf("auth.Send: smtp: %w", err)
	}
	return nil
}

// buildWireMessage formats the email per RFC 5322 with the headers
// SMTP servers expect. Plain text only; if rich HTML is ever needed it
// goes through a separate constructor.
func buildWireMessage(msg Email) string {
	var b strings.Builder
	b.WriteString("From: ")
	b.WriteString(msg.From)
	b.WriteString("\r\n")
	b.WriteString("To: ")
	b.WriteString(msg.To)
	b.WriteString("\r\n")
	b.WriteString("Subject: ")
	b.WriteString(msg.Subject)
	b.WriteString("\r\n")
	b.WriteString("MIME-Version: 1.0\r\n")
	b.WriteString("Content-Type: text/plain; charset=UTF-8\r\n")
	b.WriteString("\r\n")
	b.WriteString(msg.Body)
	return b.String()
}

// writeStdoutSink prints the email with a header rule that names the
// sink, the From/To/Subject metadata indented, and the body indented
// underneath. A bottom rule closes the block so multiple sign-in
// attempts in a row stay visually distinguishable.
//
// The rules and label render in dim ANSI on a TTY; CI / NO_COLOR
// environments get plain ASCII.
func writeStdoutSink(msg Email) {
	const width = 60
	tty := isStdoutTerminal()
	dim := wrap(tty, "\x1b[2m", "\x1b[0m")

	const label = "[mar auth] outgoing email (no SMTP configured)"
	prefix := "─── " + label + " "
	if pad := width - utf8.RuneCountInString(prefix); pad > 0 {
		prefix += strings.Repeat("─", pad)
	}
	fmt.Fprintln(os.Stdout, dim(prefix))

	fmt.Fprintf(os.Stdout, "  %s    %s\n", dim("From:"), msg.From)
	fmt.Fprintf(os.Stdout, "  %s      %s\n", dim("To:"), msg.To)
	fmt.Fprintf(os.Stdout, "  %s %s\n", dim("Subject:"), msg.Subject)
	fmt.Fprintln(os.Stdout)

	body := strings.TrimRight(msg.Body, "\n\r ")
	for _, line := range strings.Split(body, "\n") {
		if line == "" {
			fmt.Fprintln(os.Stdout)
		} else {
			fmt.Fprintf(os.Stdout, "  %s\n", line)
		}
	}

	fmt.Fprintln(os.Stdout, dim(strings.Repeat("─", width)))
	fmt.Fprintln(os.Stdout)
}

func isStdoutTerminal() bool {
	if os.Getenv("NO_COLOR") != "" {
		return false
	}
	fi, err := os.Stdout.Stat()
	return err == nil && (fi.Mode()&os.ModeCharDevice) != 0
}

func wrap(active bool, prefix, suffix string) func(string) string {
	if !active {
		return func(s string) string { return s }
	}
	return func(s string) string { return prefix + s + suffix }
}

// DefaultBody returns the framework's default email body. Subject
// carries the app's brand; body stays generic and transactional.
func DefaultBody(code string, ttlMinutes int) string {
	return fmt.Sprintf(
		"Your sign-in code is %s.\n\nIt expires in %d minutes. "+
			"If you didn't request this, you can ignore this email.\n",
		code, ttlMinutes,
	)
}
