package generator

import (
	"bytes"
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"mar/internal/model"
)

// TSClientOutput defines where the generated TypeScript client should be written.
type TSClientOutput struct {
	ModuleName string
	FileName   string
	Source     []byte
}

// GenerateTSClient builds a TypeScript module with helper functions for calling Mar APIs.
func GenerateTSClient(app *model.App) (*TSClientOutput, error) {
	if app == nil {
		return nil, fmt.Errorf("nil app")
	}
	baseModule := sanitizeModuleName(app.AppName)
	if baseModule == "" {
		baseModule = "Mar"
	}
	moduleName := baseModule + "Client"

	buf := &bytes.Buffer{}
	writeTSLine(buf, "/* Code generated by mar. DO NOT EDIT. */")
	writeTSLine(buf, "")
	writeTSLine(buf, "export type Row = Record<string, unknown>;")
	writeTSLine(buf, "")
	writeTSLine(buf, "export interface Config {")
	writeTSLine(buf, "  baseUrl: string;")
	writeTSLine(buf, "  token?: string;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "export interface FieldMeta {")
	writeTSLine(buf, "  name: string;")
	writeTSLine(buf, "  fieldType: string;")
	writeTSLine(buf, "  primary: boolean;")
	writeTSLine(buf, "  auto: boolean;")
	writeTSLine(buf, "  optional: boolean;")
	writeTSLine(buf, "  defaultValue?: unknown;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "export interface EntityMeta {")
	writeTSLine(buf, "  name: string;")
	writeTSLine(buf, "  table: string;")
	writeTSLine(buf, "  resource: string;")
	writeTSLine(buf, "  primaryKey: string;")
	writeTSLine(buf, "  fields: FieldMeta[];")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "export interface InputAliasFieldMeta {")
	writeTSLine(buf, "  name: string;")
	writeTSLine(buf, "  fieldType: string;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "export interface InputAliasMeta {")
	writeTSLine(buf, "  name: string;")
	writeTSLine(buf, "  fields: InputAliasFieldMeta[];")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "export interface ActionMeta {")
	writeTSLine(buf, "  name: string;")
	writeTSLine(buf, "  inputAlias: string;")
	writeTSLine(buf, "  steps: number;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "export interface AuthMeta {")
	writeTSLine(buf, "  enabled: boolean;")
	writeTSLine(buf, "  userEntity: string;")
	writeTSLine(buf, "  emailField: string;")
	writeTSLine(buf, "  roleField: string;")
	writeTSLine(buf, "  emailTransport: string;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "export interface SchemaMeta {")
	writeTSLine(buf, "  appName: string;")
	writeTSLine(buf, "  portNumber: number;")
	writeTSLine(buf, "  database: string;")
	writeTSLine(buf, "  entities: EntityMeta[];")
	writeTSLine(buf, "  inputAliases: InputAliasMeta[];")
	writeTSLine(buf, "  actions: ActionMeta[];")
	writeTSLine(buf, "  auth: AuthMeta | null;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "export interface RequestCodeResponse {")
	writeTSLine(buf, "  message: string;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "export interface LoginRequest {")
	writeTSLine(buf, "  email: string;")
	writeTSLine(buf, "  code: string;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "export interface LoginResponse {")
	writeTSLine(buf, "  token: string;")
	writeTSLine(buf, "  expiresAt: number;")
	writeTSLine(buf, "  user: Row;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "export interface AuthMeResponse {")
	writeTSLine(buf, "  email: string;")
	writeTSLine(buf, "  userId: unknown;")
	writeTSLine(buf, "  role: unknown;")
	writeTSLine(buf, "  user: Row;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "export interface VersionAppInfo {")
	writeTSLine(buf, "  name: string;")
	writeTSLine(buf, "  buildTime: string;")
	writeTSLine(buf, "  manifestHash: string;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "export interface PublicVersionResponse {")
	writeTSLine(buf, "  app: VersionAppInfo;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "function trimRightSlash(value: string): string {")
	writeTSLine(buf, "  return value.replace(/\\/+$/, \"\");")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "function buildUrl(config: Config, path: string): string {")
	writeTSLine(buf, "  return trimRightSlash(config.baseUrl) + path;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "function buildHeaders(config: Config): Record<string, string> {")
	writeTSLine(buf, "  const headers: Record<string, string> = { \"Content-Type\": \"application/json\" };")
	writeTSLine(buf, "  const token = (config.token ?? \"\").trim();")
	writeTSLine(buf, "  if (token !== \"\") {")
	writeTSLine(buf, "    headers.Authorization = `Bearer ${token}`;")
	writeTSLine(buf, "  }")
	writeTSLine(buf, "  return headers;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "async function parseError(response: Response): Promise<string> {")
	writeTSLine(buf, "  const text = await response.text();")
	writeTSLine(buf, "  if (!text) {")
	writeTSLine(buf, "    return `HTTP ${response.status}`;")
	writeTSLine(buf, "  }")
	writeTSLine(buf, "  return `HTTP ${response.status}: ${text}`;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "async function requestJson<T>(config: Config, method: string, path: string, payload?: unknown): Promise<T> {")
	writeTSLine(buf, "  const response = await fetch(buildUrl(config, path), {")
	writeTSLine(buf, "    method,")
	writeTSLine(buf, "    headers: buildHeaders(config),")
	writeTSLine(buf, "    body: payload === undefined ? undefined : JSON.stringify(payload),")
	writeTSLine(buf, "  });")
	writeTSLine(buf, "  if (!response.ok) {")
	writeTSLine(buf, "    throw new Error(await parseError(response));")
	writeTSLine(buf, "  }")
	writeTSLine(buf, "  if (response.status === 204) {")
	writeTSLine(buf, "    return undefined as T;")
	writeTSLine(buf, "  }")
	writeTSLine(buf, "  const text = await response.text();")
	writeTSLine(buf, "  if (!text) {")
	writeTSLine(buf, "    return undefined as T;")
	writeTSLine(buf, "  }")
	writeTSLine(buf, "  return JSON.parse(text) as T;")
	writeTSLine(buf, "}")
	writeTSLine(buf, "")
	writeTSLine(buf, "export const schema: SchemaMeta = {")
	writeTSLine(buf, "  appName: "+strconv.Quote(app.AppName)+",")
	writeTSLine(buf, "  portNumber: "+fmt.Sprintf("%d", app.Port)+",")
	writeTSLine(buf, "  database: "+strconv.Quote(app.Database)+",")
	writeTSLine(buf, "  entities: [")
	for _, entity := range app.Entities {
		writeTSLine(buf, "    {")
		writeTSLine(buf, "      name: "+strconv.Quote(entity.Name)+",")
		writeTSLine(buf, "      table: "+strconv.Quote(entity.Table)+",")
		writeTSLine(buf, "      resource: "+strconv.Quote(entity.Resource)+",")
		writeTSLine(buf, "      primaryKey: "+strconv.Quote(entity.PrimaryKey)+",")
		writeTSLine(buf, "      fields: [")
		for _, field := range entity.Fields {
			writeTSLine(buf, "        {")
			writeTSLine(buf, "          name: "+strconv.Quote(field.Name)+",")
			writeTSLine(buf, "          fieldType: "+strconv.Quote(field.Type)+",")
			writeTSLine(buf, "          primary: "+fmt.Sprintf("%t", field.Primary)+",")
			writeTSLine(buf, "          auto: "+fmt.Sprintf("%t", field.Auto)+",")
			writeTSLine(buf, "          optional: "+fmt.Sprintf("%t", field.Optional)+",")
			if field.Default != nil {
				writeTSLine(buf, "          defaultValue: "+tsLiteralFromValue(field.Default)+",")
			}
			writeTSLine(buf, "        },")
		}
		writeTSLine(buf, "      ],")
		writeTSLine(buf, "    },")
	}
	writeTSLine(buf, "  ],")
	writeTSLine(buf, "  inputAliases: [")
	for _, alias := range app.InputAliases {
		writeTSLine(buf, "    {")
		writeTSLine(buf, "      name: "+strconv.Quote(alias.Name)+",")
		writeTSLine(buf, "      fields: [")
		for _, field := range alias.Fields {
			writeTSLine(buf, "        {")
			writeTSLine(buf, "          name: "+strconv.Quote(field.Name)+",")
			writeTSLine(buf, "          fieldType: "+strconv.Quote(field.Type)+",")
			writeTSLine(buf, "        },")
		}
		writeTSLine(buf, "      ],")
		writeTSLine(buf, "    },")
	}
	writeTSLine(buf, "  ],")
	writeTSLine(buf, "  actions: [")
	for _, action := range app.Actions {
		writeTSLine(buf, "    {")
		writeTSLine(buf, "      name: "+strconv.Quote(action.Name)+",")
		writeTSLine(buf, "      inputAlias: "+strconv.Quote(action.InputAlias)+",")
		writeTSLine(buf, "      steps: "+fmt.Sprintf("%d", len(action.Steps))+",")
		writeTSLine(buf, "    },")
	}
	writeTSLine(buf, "  ],")
	if app.Auth != nil {
		writeTSLine(buf, "  auth: {")
		writeTSLine(buf, "    enabled: true,")
		writeTSLine(buf, "    userEntity: "+strconv.Quote(app.Auth.UserEntity)+",")
		writeTSLine(buf, "    emailField: "+strconv.Quote(app.Auth.EmailField)+",")
		writeTSLine(buf, "    roleField: "+strconv.Quote(app.Auth.RoleField)+",")
		writeTSLine(buf, "    emailTransport: "+strconv.Quote(app.Auth.EmailTransport)+",")
		writeTSLine(buf, "  },")
	} else {
		writeTSLine(buf, "  auth: null,")
	}
	writeTSLine(buf, "};")
	writeTSLine(buf, "")
	writeTSLine(buf, "export async function getVersion(config: Config): Promise<PublicVersionResponse> {")
	writeTSLine(buf, "  return requestJson<PublicVersionResponse>(config, \"GET\", \"/_mar/version\");")
	writeTSLine(buf, "}")

	writeTSLine(buf, "")
	for _, alias := range app.InputAliases {
		typeName := sanitizeTSIdentifier(alias.Name, "Input")
		if typeName == "" {
			continue
		}
		writeTSLine(buf, "export interface "+typeName+" {")
		for _, field := range alias.Fields {
			fieldName := sanitizeTSFieldName(field.Name)
			writeTSLine(buf, "  "+fieldName+": "+marTypeToTSType(field.Type)+";")
		}
		writeTSLine(buf, "}")
		writeTSLine(buf, "")
	}

	for _, entity := range app.Entities {
		title := sanitizeTSIdentifier(entity.Name, "Entity")
		path := entity.Resource
		if title == "" {
			continue
		}
		writeTSLine(buf, "export async function list"+title+"(config: Config): Promise<Row[]> {")
		writeTSLine(buf, "  return requestJson<Row[]>(config, \"GET\", "+strconv.Quote(path)+");")
		writeTSLine(buf, "}")
		writeTSLine(buf, "")
		writeTSLine(buf, "export async function get"+title+"(config: Config, idValue: string | number): Promise<Row> {")
		writeTSLine(buf, "  return requestJson<Row>(config, \"GET\", "+strconv.Quote(path)+" + \"/\" + encodeURIComponent(String(idValue)));")
		writeTSLine(buf, "}")
		writeTSLine(buf, "")
		writeTSLine(buf, "export async function create"+title+"(config: Config, payload: Record<string, unknown>): Promise<Row> {")
		writeTSLine(buf, "  return requestJson<Row>(config, \"POST\", "+strconv.Quote(path)+", payload);")
		writeTSLine(buf, "}")
		writeTSLine(buf, "")
		writeTSLine(buf, "export async function update"+title+"(config: Config, idValue: string | number, payload: Record<string, unknown>): Promise<Row> {")
		writeTSLine(buf, "  return requestJson<Row>(config, \"PATCH\", "+strconv.Quote(path)+" + \"/\" + encodeURIComponent(String(idValue)), payload);")
		writeTSLine(buf, "}")
		writeTSLine(buf, "")
		writeTSLine(buf, "export async function delete"+title+"(config: Config, idValue: string | number): Promise<void> {")
		writeTSLine(buf, "  await requestJson<unknown>(config, \"DELETE\", "+strconv.Quote(path)+" + \"/\" + encodeURIComponent(String(idValue)));")
		writeTSLine(buf, "}")
		writeTSLine(buf, "")
	}

	actionInputType := map[string]string{}
	for _, alias := range app.InputAliases {
		actionInputType[alias.Name] = sanitizeTSIdentifier(alias.Name, "Input")
	}
	for _, action := range app.Actions {
		title := sanitizeTSIdentifier(action.Name, "Action")
		if title == "" {
			continue
		}
		inputType := actionInputType[action.InputAlias]
		if inputType == "" {
			inputType = "Record<string, unknown>"
		}
		writeTSLine(buf, "export async function run"+title+"(config: Config, payload: "+inputType+"): Promise<Row> {")
		writeTSLine(buf, "  return requestJson<Row>(config, \"POST\", "+strconv.Quote("/actions/"+action.Name)+", payload);")
		writeTSLine(buf, "}")
		writeTSLine(buf, "")
	}

	if app.Auth != nil {
		writeTSLine(buf, "export async function requestCode(config: Config, email: string): Promise<RequestCodeResponse> {")
		writeTSLine(buf, "  return requestJson<RequestCodeResponse>(config, \"POST\", \"/auth/request-code\", { email });")
		writeTSLine(buf, "}")
		writeTSLine(buf, "")
		writeTSLine(buf, "export async function login(config: Config, payload: LoginRequest): Promise<LoginResponse> {")
		writeTSLine(buf, "  return requestJson<LoginResponse>(config, \"POST\", \"/auth/login\", payload);")
		writeTSLine(buf, "}")
		writeTSLine(buf, "")
		writeTSLine(buf, "export async function logout(config: Config): Promise<void> {")
		writeTSLine(buf, "  await requestJson<unknown>(config, \"POST\", \"/auth/logout\");")
		writeTSLine(buf, "}")
		writeTSLine(buf, "")
		writeTSLine(buf, "export async function me(config: Config): Promise<AuthMeResponse> {")
		writeTSLine(buf, "  return requestJson<AuthMeResponse>(config, \"GET\", \"/auth/me\");")
		writeTSLine(buf, "}")
	}

	out := &TSClientOutput{
		ModuleName: moduleName,
		FileName:   moduleName + ".ts",
		Source:     buf.Bytes(),
	}
	return out, nil
}

func writeTSLine(buf *bytes.Buffer, line string) {
	buf.WriteString(line)
	buf.WriteByte('\n')
}

func sanitizeTSIdentifier(value string, fallback string) string {
	cleaned := regexp.MustCompile(`[^A-Za-z0-9]+`).ReplaceAllString(value, " ")
	parts := strings.Fields(cleaned)
	if len(parts) == 0 {
		return fallback
	}
	for i := range parts {
		parts[i] = toTitle(parts[i])
	}
	joined := strings.Join(parts, "")
	if joined == "" {
		return fallback
	}
	if joined[0] >= '0' && joined[0] <= '9' {
		joined = fallback + joined
	}
	return joined
}

func sanitizeTSFieldName(value string) string {
	if regexp.MustCompile(`^[A-Za-z_$][A-Za-z0-9_$]*$`).MatchString(value) {
		return value
	}
	parts := strings.Fields(regexp.MustCompile(`[^A-Za-z0-9]+`).ReplaceAllString(value, " "))
	if len(parts) == 0 {
		return "field"
	}
	for i := 1; i < len(parts); i++ {
		parts[i] = toTitle(parts[i])
	}
	name := strings.ToLower(parts[0][:1]) + parts[0][1:]
	for i := 1; i < len(parts); i++ {
		name += parts[i]
	}
	if name == "" {
		return "field"
	}
	if name[0] >= '0' && name[0] <= '9' {
		return "field" + name
	}
	return name
}

func marTypeToTSType(typ string) string {
	switch typ {
	case "Int", "Float", "Posix":
		return "number"
	case "String":
		return "string"
	case "Bool":
		return "boolean"
	default:
		return "unknown"
	}
}

func tsLiteralFromValue(value any) string {
	switch v := value.(type) {
	case string:
		return strconv.Quote(v)
	case bool:
		if v {
			return "true"
		}
		return "false"
	case int:
		return strconv.Itoa(v)
	case int64:
		return strconv.FormatInt(v, 10)
	case float64:
		return strconv.FormatFloat(v, 'f', -1, 64)
	default:
		return "null"
	}
}
